# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\PlaneConfiguration\BODY.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1121, 569)
        self.comboBox_ITYPE = QtWidgets.QComboBox(Form)
        self.comboBox_ITYPE.setGeometry(QtCore.QRect(100, 540, 231, 22))
        self.comboBox_ITYPE.setObjectName("comboBox_ITYPE")
        self.comboBox_ITYPE.addItem("")
        self.comboBox_ITYPE.addItem("")
        self.comboBox_ITYPE.addItem("")
        self.checkBox_ITYPE = QtWidgets.QCheckBox(Form)
        self.checkBox_ITYPE.setGeometry(QtCore.QRect(30, 500, 231, 16))
        self.checkBox_ITYPE.setObjectName("checkBox_ITYPE")
        self.groupBox_Sup_Hyp = QtWidgets.QGroupBox(Form)
        self.groupBox_Sup_Hyp.setGeometry(QtCore.QRect(30, 240, 321, 181))
        self.groupBox_Sup_Hyp.setObjectName("groupBox_Sup_Hyp")
        self.label_BNOSE = QtWidgets.QLabel(self.groupBox_Sup_Hyp)
        self.label_BNOSE.setGeometry(QtCore.QRect(30, 30, 101, 21))
        self.label_BNOSE.setObjectName("label_BNOSE")
        self.label_BTAIL = QtWidgets.QLabel(self.groupBox_Sup_Hyp)
        self.label_BTAIL.setGeometry(QtCore.QRect(30, 60, 101, 21))
        self.label_BTAIL.setObjectName("label_BTAIL")
        self.label_BLN = QtWidgets.QLabel(self.groupBox_Sup_Hyp)
        self.label_BLN.setGeometry(QtCore.QRect(30, 90, 111, 21))
        self.label_BLN.setObjectName("label_BLN")
        self.label_BLA = QtWidgets.QLabel(self.groupBox_Sup_Hyp)
        self.label_BLA.setGeometry(QtCore.QRect(30, 120, 161, 21))
        self.label_BLA.setObjectName("label_BLA")
        self.checkBox_DS = QtWidgets.QCheckBox(self.groupBox_Sup_Hyp)
        self.checkBox_DS.setGeometry(QtCore.QRect(30, 150, 101, 16))
        self.checkBox_DS.setObjectName("checkBox_DS")
        self.comboBox_BNOSE = QtWidgets.QComboBox(self.groupBox_Sup_Hyp)
        self.comboBox_BNOSE.setGeometry(QtCore.QRect(180, 30, 121, 22))
        self.comboBox_BNOSE.setObjectName("comboBox_BNOSE")
        self.comboBox_BNOSE.addItem("")
        self.comboBox_BNOSE.addItem("")
        self.comboBox_BTAIL = QtWidgets.QComboBox(self.groupBox_Sup_Hyp)
        self.comboBox_BTAIL.setGeometry(QtCore.QRect(180, 60, 121, 22))
        self.comboBox_BTAIL.setObjectName("comboBox_BTAIL")
        self.comboBox_BTAIL.addItem("")
        self.comboBox_BTAIL.addItem("")
        self.lineEdit_BLN = QtWidgets.QLineEdit(self.groupBox_Sup_Hyp)
        self.lineEdit_BLN.setGeometry(QtCore.QRect(190, 90, 113, 20))
        self.lineEdit_BLN.setObjectName("lineEdit_BLN")
        self.lineEdit_BLA = QtWidgets.QLineEdit(self.groupBox_Sup_Hyp)
        self.lineEdit_BLA.setGeometry(QtCore.QRect(190, 120, 113, 20))
        self.lineEdit_BLA.setObjectName("lineEdit_BLA")
        self.lineEdit_DS = QtWidgets.QLineEdit(self.groupBox_Sup_Hyp)
        self.lineEdit_DS.setGeometry(QtCore.QRect(190, 150, 113, 20))
        self.lineEdit_DS.setObjectName("lineEdit_DS")
        self.comboBox_Conf = QtWidgets.QComboBox(Form)
        self.comboBox_Conf.setGeometry(QtCore.QRect(200, 20, 121, 22))
        self.comboBox_Conf.setObjectName("comboBox_Conf")
        self.comboBox_Conf.addItem("")
        self.comboBox_Conf.addItem("")
        self.comboBox_Conf.addItem("")
        self.comboBox_Conf.addItem("")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 450, 101, 21))
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 30, 54, 12))
        self.label.setObjectName("label")
        self.lineEdit_BODY_Num = QtWidgets.QLineEdit(Form)
        self.lineEdit_BODY_Num.setGeometry(QtCore.QRect(202, 60, 121, 20))
        self.lineEdit_BODY_Num.setObjectName("lineEdit_BODY_Num")
        self.comboBox_ComboVariables = QtWidgets.QComboBox(Form)
        self.comboBox_ComboVariables.setGeometry(QtCore.QRect(160, 90, 161, 22))
        self.comboBox_ComboVariables.setObjectName("comboBox_ComboVariables")
        self.comboBox_ComboVariables.addItem("")
        self.comboBox_ComboVariables.addItem("")
        self.comboBox_ComboVariables.addItem("")
        self.comboBox_ComboVariables.addItem("")
        self.comboBox_ComboVariables.addItem("")
        self.comboBox_ComboVariables.addItem("")
        self.image_BODY = QtWidgets.QLabel(Form)
        self.image_BODY.setGeometry(QtCore.QRect(710, 10, 391, 541))
        self.image_BODY.setText("")
        self.image_BODY.setPixmap(QtGui.QPixmap(":/card/rc_card/Body_SubSonic.png"))
        self.image_BODY.setScaledContents(False)
        self.image_BODY.setObjectName("image_BODY")
        self.groupBox_Sub = QtWidgets.QGroupBox(Form)
        self.groupBox_Sub.setGeometry(QtCore.QRect(30, 130, 321, 81))
        self.groupBox_Sub.setObjectName("groupBox_Sub")
        self.pushButton_ZU = QtWidgets.QPushButton(self.groupBox_Sub)
        self.pushButton_ZU.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.pushButton_ZU.setObjectName("pushButton_ZU")
        self.pushButton_ZL = QtWidgets.QPushButton(self.groupBox_Sub)
        self.pushButton_ZL.setGeometry(QtCore.QRect(20, 50, 75, 23))
        self.pushButton_ZL.setObjectName("pushButton_ZL")
        self.Tab_ComboVariables = QtWidgets.QTableWidget(Form)
        self.Tab_ComboVariables.setGeometry(QtCore.QRect(360, 0, 331, 571))
        self.Tab_ComboVariables.setObjectName("Tab_ComboVariables")
        self.Tab_ComboVariables.setColumnCount(0)
        self.Tab_ComboVariables.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 131, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox_METHED = QtWidgets.QComboBox(Form)
        self.comboBox_METHED.setGeometry(QtCore.QRect(150, 450, 181, 22))
        self.comboBox_METHED.setObjectName("comboBox_METHED")
        self.comboBox_METHED.addItem("")
        self.comboBox_METHED.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox_ITYPE.setItemText(0, _translate("Form", "1. 直翼，不计算面积效应(Area Rule)"))
        self.comboBox_ITYPE.setItemText(1, _translate("Form", "2. 掠翼，不计算面积效应(系统默认)"))
        self.comboBox_ITYPE.setItemText(2, _translate("Form", "3. 掠翼，计算面积效应"))
        self.checkBox_ITYPE.setText(_translate("Form", "ITYPE:跨音速阻力分量马赫数计算方法"))
        self.groupBox_Sup_Hyp.setTitle(_translate("Form", "超声速、高超声速布局"))
        self.label_BNOSE.setText(_translate("Form", "BNOSE：机头样式"))
        self.label_BTAIL.setText(_translate("Form", "BTAIL：机尾样式"))
        self.label_BLN.setText(_translate("Form", "BLN：机身机头长度"))
        self.label_BLA.setText(_translate("Form", "BLA：圆柱状后机身部分长度"))
        self.checkBox_DS.setText(_translate("Form", "DS：机头钝度"))
        self.comboBox_BNOSE.setItemText(0, _translate("Form", "1.0 圆锥型机头"))
        self.comboBox_BNOSE.setItemText(1, _translate("Form", "2.0 尖型机头"))
        self.comboBox_BTAIL.setItemText(0, _translate("Form", "1.0 圆锥型机尾"))
        self.comboBox_BTAIL.setItemText(1, _translate("Form", "2.0 尖型机尾"))
        self.comboBox_Conf.setItemText(0, _translate("Form", "亚音速-轴对称体"))
        self.comboBox_Conf.setItemText(1, _translate("Form", "亚音速-非对称体"))
        self.comboBox_Conf.setItemText(2, _translate("Form", "超音速"))
        self.comboBox_Conf.setItemText(3, _translate("Form", "高超音速"))
        self.label_8.setText(_translate("Form", "METHED：计算方法"))
        self.label_2.setText(_translate("Form", "NX：机身横截面的个数"))
        self.label.setText(_translate("Form", "布局选择"))
        self.comboBox_ComboVariables.setItemText(0, _translate("Form", "R  -只输入半径（超声速/高超声速 、亚音速轴对称）"))
        self.comboBox_ComboVariables.setItemText(1, _translate("Form", "S  -只输入面积（超声速/高超声速 、亚音速轴对称）"))
        self.comboBox_ComboVariables.setItemText(2, _translate("Form", "P  -只输入周长（超声速/高超声速 、亚音速轴对称）"))
        self.comboBox_ComboVariables.setItemText(3, _translate("Form", "S+P  - R=sqrt（S/pi）"))
        self.comboBox_ComboVariables.setItemText(4, _translate("Form", "P+R  - S=pi*R^2"))
        self.comboBox_ComboVariables.setItemText(5, _translate("Form", "S+R  - P=2πR，其中是R= sqrt（S/pi）或输入的R中较大的那个"))
        self.groupBox_Sub.setTitle(_translate("Form", "亚音速布局"))
        self.pushButton_ZU.setText(_translate("Form", "ZU："))
        self.pushButton_ZL.setText(_translate("Form", "ZL："))
        self.label_3.setText(_translate("Form", "机身横截面参数组合"))
        self.comboBox_METHED.setItemText(0, _translate("Form", "1. 使用现有方法（系统默认）"))
        self.comboBox_METHED.setItemText(1, _translate("Form", "2. 使用Jorgensen方法"))

import cardInfo_rc
import card_rc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

