# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\PlaneConfiguration\BODY.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1072, 510)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(73, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.comboBox_SpeedRegime = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_SpeedRegime.setObjectName("comboBox_SpeedRegime")
        self.comboBox_SpeedRegime.addItem("")
        self.comboBox_SpeedRegime.addItem("")
        self.comboBox_SpeedRegime.addItem("")
        self.comboBox_SpeedRegime.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_SpeedRegime)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(31, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.NX = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NX.sizePolicy().hasHeightForWidth())
        self.NX.setSizePolicy(sizePolicy)
        self.NX.setObjectName("NX")
        self.horizontalLayout_2.addWidget(self.NX)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_Sub = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Sub.sizePolicy().hasHeightForWidth())
        self.groupBox_Sub.setSizePolicy(sizePolicy)
        self.groupBox_Sub.setTitle("")
        self.groupBox_Sub.setObjectName("groupBox_Sub")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_Sub)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_Sub)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.comboBox_VarCombo = QtWidgets.QComboBox(self.groupBox_Sub)
        self.comboBox_VarCombo.setObjectName("comboBox_VarCombo")
        self.comboBox_VarCombo.addItem("")
        self.comboBox_VarCombo.addItem("")
        self.comboBox_VarCombo.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_VarCombo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_ELLIP = QtWidgets.QCheckBox(self.groupBox_Sub)
        self.checkBox_ELLIP.setObjectName("checkBox_ELLIP")
        self.horizontalLayout_12.addWidget(self.checkBox_ELLIP)
        spacerItem4 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.ELLIP = QtWidgets.QLineEdit(self.groupBox_Sub)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ELLIP.sizePolicy().hasHeightForWidth())
        self.ELLIP.setSizePolicy(sizePolicy)
        self.ELLIP.setObjectName("ELLIP")
        self.horizontalLayout_12.addWidget(self.ELLIP)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox_Sub)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.comboBox_METHED = QtWidgets.QComboBox(self.groupBox_Sub)
        self.comboBox_METHED.setObjectName("comboBox_METHED")
        self.comboBox_METHED.addItem("")
        self.comboBox_METHED.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_METHED)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addWidget(self.groupBox_Sub)
        self.groupBox_Sup_Hyp = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Sup_Hyp.sizePolicy().hasHeightForWidth())
        self.groupBox_Sup_Hyp.setSizePolicy(sizePolicy)
        self.groupBox_Sup_Hyp.setTitle("")
        self.groupBox_Sup_Hyp.setObjectName("groupBox_Sup_Hyp")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Sup_Hyp)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_BNOSE = QtWidgets.QCheckBox(self.groupBox_Sup_Hyp)
        self.checkBox_BNOSE.setObjectName("checkBox_BNOSE")
        self.horizontalLayout_4.addWidget(self.checkBox_BNOSE)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.comboBox_BNOSE = QtWidgets.QComboBox(self.groupBox_Sup_Hyp)
        self.comboBox_BNOSE.setObjectName("comboBox_BNOSE")
        self.comboBox_BNOSE.addItem("")
        self.comboBox_BNOSE.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_BNOSE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_BTAIL = QtWidgets.QCheckBox(self.groupBox_Sup_Hyp)
        self.checkBox_BTAIL.setObjectName("checkBox_BTAIL")
        self.horizontalLayout_5.addWidget(self.checkBox_BTAIL)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.comboBox_BTAIL = QtWidgets.QComboBox(self.groupBox_Sup_Hyp)
        self.comboBox_BTAIL.setObjectName("comboBox_BTAIL")
        self.comboBox_BTAIL.addItem("")
        self.comboBox_BTAIL.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_BTAIL)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_BLN = QtWidgets.QCheckBox(self.groupBox_Sup_Hyp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_BLN.sizePolicy().hasHeightForWidth())
        self.checkBox_BLN.setSizePolicy(sizePolicy)
        self.checkBox_BLN.setObjectName("checkBox_BLN")
        self.horizontalLayout_6.addWidget(self.checkBox_BLN)
        self.label_BLN = QtWidgets.QLabel(self.groupBox_Sup_Hyp)
        self.label_BLN.setText("")
        self.label_BLN.setObjectName("label_BLN")
        self.horizontalLayout_6.addWidget(self.label_BLN)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.BLN = QtWidgets.QLineEdit(self.groupBox_Sup_Hyp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BLN.sizePolicy().hasHeightForWidth())
        self.BLN.setSizePolicy(sizePolicy)
        self.BLN.setObjectName("BLN")
        self.horizontalLayout_6.addWidget(self.BLN)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_BLA = QtWidgets.QCheckBox(self.groupBox_Sup_Hyp)
        self.checkBox_BLA.setObjectName("checkBox_BLA")
        self.horizontalLayout_7.addWidget(self.checkBox_BLA)
        self.label_BLA = QtWidgets.QLabel(self.groupBox_Sup_Hyp)
        self.label_BLA.setText("")
        self.label_BLA.setObjectName("label_BLA")
        self.horizontalLayout_7.addWidget(self.label_BLA)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.BLA = QtWidgets.QLineEdit(self.groupBox_Sup_Hyp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BLA.sizePolicy().hasHeightForWidth())
        self.BLA.setSizePolicy(sizePolicy)
        self.BLA.setObjectName("BLA")
        self.horizontalLayout_7.addWidget(self.BLA)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_DS = QtWidgets.QCheckBox(self.groupBox_Sup_Hyp)
        self.checkBox_DS.setObjectName("checkBox_DS")
        self.horizontalLayout_8.addWidget(self.checkBox_DS)
        spacerItem10 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.DS = QtWidgets.QLineEdit(self.groupBox_Sup_Hyp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DS.sizePolicy().hasHeightForWidth())
        self.DS.setSizePolicy(sizePolicy)
        self.DS.setObjectName("DS")
        self.horizontalLayout_8.addWidget(self.DS)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.groupBox_Sup_Hyp)
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_ITYPE = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ITYPE.sizePolicy().hasHeightForWidth())
        self.checkBox_ITYPE.setSizePolicy(sizePolicy)
        self.checkBox_ITYPE.setObjectName("checkBox_ITYPE")
        self.horizontalLayout_10.addWidget(self.checkBox_ITYPE)
        spacerItem11 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem12 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.comboBox_ITYPE = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_ITYPE.setObjectName("comboBox_ITYPE")
        self.comboBox_ITYPE.addItem("")
        self.comboBox_ITYPE.addItem("")
        self.comboBox_ITYPE.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_ITYPE)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.horizontalLayout_15.addLayout(self.verticalLayout)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tableWidget_BODY = QtWidgets.QTableWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_BODY.sizePolicy().hasHeightForWidth())
        self.tableWidget_BODY.setSizePolicy(sizePolicy)
        self.tableWidget_BODY.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_BODY.setObjectName("tableWidget_BODY")
        self.tableWidget_BODY.setColumnCount(0)
        self.tableWidget_BODY.setRowCount(0)
        self.horizontalLayout_14.addWidget(self.tableWidget_BODY)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 32))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.image_BODY = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_BODY.sizePolicy().hasHeightForWidth())
        self.image_BODY.setSizePolicy(sizePolicy)
        self.image_BODY.setText("")
        self.image_BODY.setPixmap(QtGui.QPixmap(":/card/rc_card/Body_SubSonic.png"))
        self.image_BODY.setScaledContents(False)
        self.image_BODY.setObjectName("image_BODY")
        self.verticalLayout_6.addWidget(self.image_BODY)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_16.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 98, 32))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.imageBoDY2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.imageBoDY2.setText("")
        self.imageBoDY2.setPixmap(QtGui.QPixmap(":/card/rc_card/Body_SuperSonic.png"))
        self.imageBoDY2.setScaledContents(False)
        self.imageBoDY2.setObjectName("imageBoDY2")
        self.verticalLayout_7.addWidget(self.imageBoDY2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_17.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_13.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_15.addWidget(self.tabWidget)
        self.actionAddRow = QtWidgets.QAction(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cardIco/rc_card/icos/AddedIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddRow.setIcon(icon)
        self.actionAddRow.setObjectName("actionAddRow")
        self.actionDeleteRow = QtWidgets.QAction(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/cardIco/rc_card/icos/DeletedIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteRow.setIcon(icon1)
        self.actionDeleteRow.setObjectName("actionDeleteRow")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.comboBox_SpeedRegime, self.NX)
        Form.setTabOrder(self.NX, self.comboBox_VarCombo)
        Form.setTabOrder(self.comboBox_VarCombo, self.checkBox_ELLIP)
        Form.setTabOrder(self.checkBox_ELLIP, self.ELLIP)
        Form.setTabOrder(self.ELLIP, self.comboBox_BNOSE)
        Form.setTabOrder(self.comboBox_BNOSE, self.comboBox_BTAIL)
        Form.setTabOrder(self.comboBox_BTAIL, self.BLN)
        Form.setTabOrder(self.BLN, self.BLA)
        Form.setTabOrder(self.BLA, self.checkBox_DS)
        Form.setTabOrder(self.checkBox_DS, self.DS)
        Form.setTabOrder(self.DS, self.comboBox_METHED)
        Form.setTabOrder(self.comboBox_METHED, self.checkBox_ITYPE)
        Form.setTabOrder(self.checkBox_ITYPE, self.comboBox_ITYPE)
        Form.setTabOrder(self.comboBox_ITYPE, self.tableWidget_BODY)
        Form.setTabOrder(self.tableWidget_BODY, self.plainTextEdit)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "机体参数"))
        self.label.setText(_translate("Form", "布局选择"))
        self.comboBox_SpeedRegime.setItemText(0, _translate("Form", "亚音速"))
        self.comboBox_SpeedRegime.setItemText(1, _translate("Form", "跨音速"))
        self.comboBox_SpeedRegime.setItemText(2, _translate("Form", "超音速"))
        self.comboBox_SpeedRegime.setItemText(3, _translate("Form", "高超音速"))
        self.label_2.setText(_translate("Form", "NX：机身横截面的个数"))
        self.label_3.setText(_translate("Form", "机身横截面参数组合"))
        self.comboBox_VarCombo.setItemText(0, _translate("Form", "X-R-ZU-ZL"))
        self.comboBox_VarCombo.setItemText(1, _translate("Form", "X-S-ZU-ZL"))
        self.comboBox_VarCombo.setItemText(2, _translate("Form", "X-R-S-P-ZU-ZL  "))
        self.checkBox_ELLIP.setText(_translate("Form", "ELLIP：机身高宽比"))
        self.label_8.setText(_translate("Form", "METHED：计算方法"))
        self.comboBox_METHED.setItemText(0, _translate("Form", "1. 使用现有方法（系统默认）"))
        self.comboBox_METHED.setItemText(1, _translate("Form", "2. 使用Jorgensen方法"))
        self.checkBox_BNOSE.setText(_translate("Form", "BNOSE：机头样式"))
        self.comboBox_BNOSE.setItemText(0, _translate("Form", "1.0 圆锥型机头"))
        self.comboBox_BNOSE.setItemText(1, _translate("Form", "2.0 尖型机头"))
        self.checkBox_BTAIL.setText(_translate("Form", "BTAIL：机尾样式"))
        self.comboBox_BTAIL.setItemText(0, _translate("Form", "1.0 圆锥型机尾"))
        self.comboBox_BTAIL.setItemText(1, _translate("Form", "2.0 尖型机尾"))
        self.checkBox_BLN.setText(_translate("Form", "BLN：机身头部长度"))
        self.checkBox_BLA.setToolTip(_translate("Form", "圆柱状后机身部分长度"))
        self.checkBox_BLA.setText(_translate("Form", "BLA：机身后部长度"))
        self.checkBox_DS.setText(_translate("Form", "DS：机头钝度"))
        self.checkBox_ITYPE.setText(_translate("Form", "ITYPE:跨音速阻力分量马赫数计算方法"))
        self.comboBox_ITYPE.setItemText(0, _translate("Form", "1. 直翼，不计算面积效应(Area Rule)"))
        self.comboBox_ITYPE.setItemText(1, _translate("Form", "2. 掠翼，不计算面积效应(系统默认)"))
        self.comboBox_ITYPE.setItemText(2, _translate("Form", "3. 掠翼，计算面积效应"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "机身参数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "机身参数示意"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "机身参数示意"))
        self.plainTextEdit.setPlainText(_translate("Form", "本节主要录入机体的参数\n"
"NX : 机身定义位置的数量，最大20\n"
"X  : 机身截面的纵向距离，最大20\n"
"S  : 横截面面积（cross sectional area）\n"
"P  : 周长（periphery）\n"
"R  : 半径（local planform half width）\n"
"ELLIP : ELLIP = 高度A/宽度B,>1表示高而窄\n"
"ZU : 截面处机体上表面的Z坐标（中线以上为正）\n"
"ZL : 截面处机体下表面的Z坐标（中线以下为负）\n"
"\n"
"Tips 1:截面参数模式\n"
"A1. 只使用R或者S，其他参数按照圆截面估计；\n"
"A2. 如果ELLIP被定义，从R或者S估计其他参数，ELLIP = 高度A/宽度B,>1表示高而窄；此处必须使用METHOD=2.0\n"
"A3. R,S,P都定义\n"
"Tips 2;参考截面说明\n"
"参考平面 = 轴对称机体的堆成轴\n"
"Tips 3：\n"
"机体中线线处Z=0\n"
"Tips 4：\n"
"BNOSE BTAIL BLN BLA 这些参数在亚音速域不需要\n"
"Tips 5：\n"
"DS 只在高超声速需要 （Hypersonic Speed Regime Oonly）\n"
"\n"
"Tips 6：\n"
"在跨声速和超声速是由S得到等效半径 Req = sqrt(S/π)\n"
"\n"
"Tips 7：在Lbt =0 是忽略BTAIL，即无尾时"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "参数说明"))
        self.actionAddRow.setText(_translate("Form", "增加行"))
        self.actionAddRow.setToolTip(_translate("Form", "新增行"))
        self.actionDeleteRow.setText(_translate("Form", "删除行"))
        self.actionDeleteRow.setToolTip(_translate("Form", "删除一行"))

import card_ico_rc
import card_rc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

