# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\PlaneConfiguration\EXPR.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1071, 624)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_CDV = QtWidgets.QCheckBox(Form)
        self.checkBox_CDV.setObjectName("checkBox_CDV")
        self.horizontalLayout.addWidget(self.checkBox_CDV)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.CDV = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CDV.sizePolicy().hasHeightForWidth())
        self.CDV.setSizePolicy(sizePolicy)
        self.CDV.setObjectName("CDV")
        self.horizontalLayout.addWidget(self.CDV)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_ALPOW = QtWidgets.QCheckBox(Form)
        self.checkBox_ALPOW.setObjectName("checkBox_ALPOW")
        self.horizontalLayout_2.addWidget(self.checkBox_ALPOW)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.ALPOW = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ALPOW.sizePolicy().hasHeightForWidth())
        self.ALPOW.setSizePolicy(sizePolicy)
        self.ALPOW.setObjectName("ALPOW")
        self.horizontalLayout_2.addWidget(self.ALPOW)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_ALPLW = QtWidgets.QCheckBox(Form)
        self.checkBox_ALPLW.setObjectName("checkBox_ALPLW")
        self.horizontalLayout_3.addWidget(self.checkBox_ALPLW)
        spacerItem3 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.ALPLW = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ALPLW.sizePolicy().hasHeightForWidth())
        self.ALPLW.setSizePolicy(sizePolicy)
        self.ALPLW.setObjectName("ALPLW")
        self.horizontalLayout_3.addWidget(self.ALPLW)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_ACLMW = QtWidgets.QCheckBox(Form)
        self.checkBox_ACLMW.setObjectName("checkBox_ACLMW")
        self.horizontalLayout_6.addWidget(self.checkBox_ACLMW)
        spacerItem4 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.ACLMW = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ACLMW.sizePolicy().hasHeightForWidth())
        self.ACLMW.setSizePolicy(sizePolicy)
        self.ACLMW.setObjectName("ACLMW")
        self.horizontalLayout_6.addWidget(self.ACLMW)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_CLMW = QtWidgets.QCheckBox(Form)
        self.checkBox_CLMW.setObjectName("checkBox_CLMW")
        self.horizontalLayout_5.addWidget(self.checkBox_CLMW)
        spacerItem5 = QtWidgets.QSpacerItem(37, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.CLMW = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CLMW.sizePolicy().hasHeightForWidth())
        self.CLMW.setSizePolicy(sizePolicy)
        self.CLMW.setObjectName("CLMW")
        self.horizontalLayout_5.addWidget(self.CLMW)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_ALPOH = QtWidgets.QCheckBox(Form)
        self.checkBox_ALPOH.setObjectName("checkBox_ALPOH")
        self.horizontalLayout_4.addWidget(self.checkBox_ALPOH)
        spacerItem6 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.ALPOH = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ALPOH.sizePolicy().hasHeightForWidth())
        self.ALPOH.setSizePolicy(sizePolicy)
        self.ALPOH.setObjectName("ALPOH")
        self.horizontalLayout_4.addWidget(self.ALPOH)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_ALPLH = QtWidgets.QCheckBox(Form)
        self.checkBox_ALPLH.setObjectName("checkBox_ALPLH")
        self.horizontalLayout_7.addWidget(self.checkBox_ALPLH)
        spacerItem7 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.ALPLH = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ALPLH.sizePolicy().hasHeightForWidth())
        self.ALPLH.setSizePolicy(sizePolicy)
        self.ALPLH.setObjectName("ALPLH")
        self.horizontalLayout_7.addWidget(self.ALPLH)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_ACLMH = QtWidgets.QCheckBox(Form)
        self.checkBox_ACLMH.setObjectName("checkBox_ACLMH")
        self.horizontalLayout_8.addWidget(self.checkBox_ACLMH)
        spacerItem8 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.ACLMH = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ACLMH.sizePolicy().hasHeightForWidth())
        self.ACLMH.setSizePolicy(sizePolicy)
        self.ACLMH.setObjectName("ACLMH")
        self.horizontalLayout_8.addWidget(self.ACLMH)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_CLMH = QtWidgets.QCheckBox(Form)
        self.checkBox_CLMH.setObjectName("checkBox_CLMH")
        self.horizontalLayout_9.addWidget(self.checkBox_CLMH)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.CLMH = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CLMH.sizePolicy().hasHeightForWidth())
        self.CLMH.setSizePolicy(sizePolicy)
        self.CLMH.setObjectName("CLMH")
        self.horizontalLayout_9.addWidget(self.CLMH)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.tabWidget_all = QtWidgets.QTabWidget(Form)
        self.tabWidget_all.setObjectName("tabWidget_all")
        self.tab_Body = QtWidgets.QWidget()
        self.tab_Body.setObjectName("tab_Body")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_Body)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_Body = QtWidgets.QTableWidget(self.tab_Body)
        self.tableWidget_Body.setObjectName("tableWidget_Body")
        self.tableWidget_Body.setColumnCount(0)
        self.tableWidget_Body.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_Body)
        self.tabWidget_all.addTab(self.tab_Body, "")
        self.tab_Wing = QtWidgets.QWidget()
        self.tab_Wing.setObjectName("tab_Wing")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_Wing)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_Wing = QtWidgets.QTableWidget(self.tab_Wing)
        self.tableWidget_Wing.setObjectName("tableWidget_Wing")
        self.tableWidget_Wing.setColumnCount(0)
        self.tableWidget_Wing.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_Wing)
        self.tabWidget_all.addTab(self.tab_Wing, "")
        self.tab_HorizontolTail = QtWidgets.QWidget()
        self.tab_HorizontolTail.setObjectName("tab_HorizontolTail")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_HorizontolTail)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget_HorizontalTail = QtWidgets.QTableWidget(self.tab_HorizontolTail)
        self.tableWidget_HorizontalTail.setObjectName("tableWidget_HorizontalTail")
        self.tableWidget_HorizontalTail.setColumnCount(0)
        self.tableWidget_HorizontalTail.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget_HorizontalTail)
        self.tabWidget_all.addTab(self.tab_HorizontolTail, "")
        self.tab_WingBody = QtWidgets.QWidget()
        self.tab_WingBody.setObjectName("tab_WingBody")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_WingBody)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget_WingBody = QtWidgets.QTableWidget(self.tab_WingBody)
        self.tableWidget_WingBody.setObjectName("tableWidget_WingBody")
        self.tableWidget_WingBody.setColumnCount(0)
        self.tableWidget_WingBody.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidget_WingBody)
        self.tabWidget_all.addTab(self.tab_WingBody, "")
        self.tab_Downwash = QtWidgets.QWidget()
        self.tab_Downwash.setObjectName("tab_Downwash")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_Downwash)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidget_Downwash = QtWidgets.QTableWidget(self.tab_Downwash)
        self.tableWidget_Downwash.setObjectName("tableWidget_Downwash")
        self.tableWidget_Downwash.setColumnCount(0)
        self.tableWidget_Downwash.setRowCount(0)
        self.verticalLayout_8.addWidget(self.tableWidget_Downwash)
        self.tabWidget_all.addTab(self.tab_Downwash, "")
        self.tab_Help = QtWidgets.QWidget()
        self.tab_Help.setObjectName("tab_Help")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_Help)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textBrowser_help = QtWidgets.QTextBrowser(self.tab_Help)
        self.textBrowser_help.setObjectName("textBrowser_help")
        self.verticalLayout_7.addWidget(self.textBrowser_help)
        self.tabWidget_all.addTab(self.tab_Help, "")
        self.horizontalLayout_10.addWidget(self.tabWidget_all)

        self.retranslateUi(Form)
        self.tabWidget_all.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_CDV.setText(_translate("Form", "CDV    垂尾零升阻力系数   "))
        self.checkBox_ALPOW.setToolTip(_translate("Form", "wing zero lift angle of attack ，deg                                 机翼零升攻角"))
        self.checkBox_ALPOW.setText(_translate("Form", "ALPOW  机翼零升攻角"))
        self.ALPOW.setToolTip(_translate("Form", "wing zero lift angle of attack ，deg                                 机翼零升攻角"))
        self.checkBox_ALPLW.setToolTip(_translate("Form", "ALPLW  机翼升力非线性化的攻角"))
        self.checkBox_ALPLW.setText(_translate("Form", "ALPLW  机翼升力非线性化的攻角"))
        self.ALPLW.setToolTip(_translate("Form", "wing angle of attack where lift becomes non-linear，deg              机翼升力非线性化的攻角 "))
        self.checkBox_ACLMW.setToolTip(_translate("Form", "wing angle of attack for max. lift，deg                              机翼最大升力的攻角"))
        self.checkBox_ACLMW.setText(_translate("Form", "ACLMW  机翼最大升力的攻角"))
        self.ACLMW.setToolTip(_translate("Form", "wing angle of attack for max. lift，deg                              机翼最大升力的攻角"))
        self.checkBox_CLMW.setToolTip(_translate("Form", "wing max. LIFT coefficient                                           机翼最大升力系数"))
        self.checkBox_CLMW.setText(_translate("Form", "CLMW   机翼最大升力系数"))
        self.CLMW.setToolTip(_translate("Form", "wing max. LIFT coefficient                                           机翼最大升力系数"))
        self.checkBox_ALPOH.setToolTip(_translate("Form", "horizontal tail zero lift angle of attack，deg                       水平尾翼零升攻角"))
        self.checkBox_ALPOH.setText(_translate("Form", "ALPOH  水平尾翼零升攻角 "))
        self.ALPOH.setToolTip(_translate("Form", "horizontal tail zero lift angle of attack，deg                       水平尾翼零升攻角"))
        self.checkBox_ALPLH.setToolTip(_translate("Form", "horizontal tail angle of attack where lift becomes non-linear，deg   水平尾翼升力非线性化的攻角"))
        self.checkBox_ALPLH.setText(_translate("Form", "ALPLH  水平尾翼升力非线性化的攻角"))
        self.ALPLH.setToolTip(_translate("Form", "horizontal tail angle of attack where lift becomes non-linear，deg   水平尾翼升力非线性化的攻角"))
        self.checkBox_ACLMH.setToolTip(_translate("Form", "horizontal tail angle of attack for max. lift，deg                   水平尾翼最大升力的攻角horizontal tail angle of attack for max. lift，deg                   水平尾翼最大升力的攻角"))
        self.checkBox_ACLMH.setText(_translate("Form", "ACLMH  水平尾翼最大升力的攻角"))
        self.ACLMH.setToolTip(_translate("Form", "horizontal tail angle of attack for max. lift，deg                   水平尾翼最大升力的攻角"))
        self.checkBox_CLMH.setToolTip(_translate("Form", "horizontal tail max. LIFT coefficient                                水平尾翼最大升力系数"))
        self.checkBox_CLMH.setText(_translate("Form", "CLMH   水平尾翼最大升力系数"))
        self.CLMH.setToolTip(_translate("Form", "horizontal tail max. LIFT coefficient                                水平尾翼最大升力系数"))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_Body), _translate("Form", "机体参数"))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_Wing), _translate("Form", "机翼试验参数"))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_HorizontolTail), _translate("Form", "水平尾翼试验参数"))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_WingBody), _translate("Form", "翼身试验参数"))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_Downwash), _translate("Form", "下洗"))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_Help), _translate("Form", "帮助说明"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

