# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\PlaneConfiguration\FLTCON.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FLTCON(object):
    def setupUi(self, FLTCON):
        FLTCON.setObjectName("FLTCON")
        FLTCON.resize(925, 528)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(FLTCON)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.TopLayout = QtWidgets.QVBoxLayout()
        self.TopLayout.setObjectName("TopLayout")
        self.groupBox_flt = QtWidgets.QGroupBox(FLTCON)
        self.groupBox_flt.setObjectName("groupBox_flt")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_flt)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.groupBox_flt)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.comboBox_LOOP = QtWidgets.QComboBox(self.groupBox_flt)
        self.comboBox_LOOP.setObjectName("comboBox_LOOP")
        self.comboBox_LOOP.addItem("")
        self.comboBox_LOOP.addItem("")
        self.comboBox_LOOP.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_LOOP)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox_flt)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.comboBox_Variables = QtWidgets.QComboBox(self.groupBox_flt)
        self.comboBox_Variables.setObjectName("comboBox_Variables")
        self.comboBox_Variables.addItem("")
        self.comboBox_Variables.addItem("")
        self.comboBox_Variables.addItem("")
        self.comboBox_Variables.addItem("")
        self.comboBox_Variables.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_Variables)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_UsingNACA = QtWidgets.QCheckBox(self.groupBox_flt)
        self.checkBox_UsingNACA.setObjectName("checkBox_UsingNACA")
        self.horizontalLayout_9.addWidget(self.checkBox_UsingNACA)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.groupBox_flt)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.NMACH = QtWidgets.QLineEdit(self.groupBox_flt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NMACH.sizePolicy().hasHeightForWidth())
        self.NMACH.setSizePolicy(sizePolicy)
        self.NMACH.setObjectName("NMACH")
        self.horizontalLayout_10.addWidget(self.NMACH)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.groupBox_flt)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.NALT = QtWidgets.QLineEdit(self.groupBox_flt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NALT.sizePolicy().hasHeightForWidth())
        self.NALT.setSizePolicy(sizePolicy)
        self.NALT.setObjectName("NALT")
        self.horizontalLayout_12.addWidget(self.NALT)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.groupBox_flt)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.NALPHA = QtWidgets.QLineEdit(self.groupBox_flt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NALPHA.sizePolicy().hasHeightForWidth())
        self.NALPHA.setSizePolicy(sizePolicy)
        self.NALPHA.setObjectName("NALPHA")
        self.horizontalLayout_11.addWidget(self.NALPHA)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.TopLayout.addWidget(self.groupBox_flt)
        self.groupBox_otherFlt = QtWidgets.QGroupBox(FLTCON)
        self.groupBox_otherFlt.setObjectName("groupBox_otherFlt")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_otherFlt)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_WT = QtWidgets.QCheckBox(self.groupBox_otherFlt)
        self.checkBox_WT.setObjectName("checkBox_WT")
        self.horizontalLayout_5.addWidget(self.checkBox_WT)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.WT = QtWidgets.QLineEdit(self.groupBox_otherFlt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WT.sizePolicy().hasHeightForWidth())
        self.WT.setSizePolicy(sizePolicy)
        self.WT.setObjectName("WT")
        self.horizontalLayout_5.addWidget(self.WT)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_GAMMA = QtWidgets.QCheckBox(self.groupBox_otherFlt)
        self.checkBox_GAMMA.setObjectName("checkBox_GAMMA")
        self.horizontalLayout_6.addWidget(self.checkBox_GAMMA)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.GAMMA = QtWidgets.QLineEdit(self.groupBox_otherFlt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GAMMA.sizePolicy().hasHeightForWidth())
        self.GAMMA.setSizePolicy(sizePolicy)
        self.GAMMA.setObjectName("GAMMA")
        self.horizontalLayout_6.addWidget(self.GAMMA)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.TopLayout.addWidget(self.groupBox_otherFlt)
        self.groupBox_options = QtWidgets.QGroupBox(FLTCON)
        self.groupBox_options.setObjectName("groupBox_options")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_options)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_STMACH = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_STMACH.setObjectName("checkBox_STMACH")
        self.horizontalLayout.addWidget(self.checkBox_STMACH)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.STMACH = QtWidgets.QLineEdit(self.groupBox_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.STMACH.sizePolicy().hasHeightForWidth())
        self.STMACH.setSizePolicy(sizePolicy)
        self.STMACH.setObjectName("STMACH")
        self.horizontalLayout.addWidget(self.STMACH)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_TSMACH = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_TSMACH.setObjectName("checkBox_TSMACH")
        self.horizontalLayout_2.addWidget(self.checkBox_TSMACH)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.TSMACH = QtWidgets.QLineEdit(self.groupBox_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TSMACH.sizePolicy().hasHeightForWidth())
        self.TSMACH.setSizePolicy(sizePolicy)
        self.TSMACH.setObjectName("TSMACH")
        self.horizontalLayout_2.addWidget(self.TSMACH)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_HYPERS = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_HYPERS.setObjectName("checkBox_HYPERS")
        self.horizontalLayout_3.addWidget(self.checkBox_HYPERS)
        spacerItem10 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.comboBox_HYPERS = QtWidgets.QComboBox(self.groupBox_options)
        self.comboBox_HYPERS.setObjectName("comboBox_HYPERS")
        self.comboBox_HYPERS.addItem("")
        self.comboBox_HYPERS.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_HYPERS)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_TR = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_TR.setObjectName("checkBox_TR")
        self.horizontalLayout_4.addWidget(self.checkBox_TR)
        spacerItem11 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.comboBox_TR = QtWidgets.QComboBox(self.groupBox_options)
        self.comboBox_TR.setObjectName("comboBox_TR")
        self.comboBox_TR.addItem("")
        self.comboBox_TR.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_TR)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.TopLayout.addWidget(self.groupBox_options)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.TopLayout.addItem(spacerItem12)
        self.horizontalLayout_14.addLayout(self.TopLayout)
        self.tabWidget_right = QtWidgets.QTabWidget(FLTCON)
        self.tabWidget_right.setObjectName("tabWidget_right")
        self.tab_PARA = QtWidgets.QWidget()
        self.tab_PARA.setObjectName("tab_PARA")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.tab_PARA)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tableWidget_ALSCHD = QtWidgets.QTableWidget(self.tab_PARA)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_ALSCHD.sizePolicy().hasHeightForWidth())
        self.tableWidget_ALSCHD.setSizePolicy(sizePolicy)
        self.tableWidget_ALSCHD.setMaximumSize(QtCore.QSize(120, 16777215))
        self.tableWidget_ALSCHD.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget_ALSCHD.setObjectName("tableWidget_ALSCHD")
        self.tableWidget_ALSCHD.setColumnCount(0)
        self.tableWidget_ALSCHD.setRowCount(0)
        self.horizontalLayout_13.addWidget(self.tableWidget_ALSCHD)
        self.tableWidget_Speed_Atmospheric = QtWidgets.QTableWidget(self.tab_PARA)
        self.tableWidget_Speed_Atmospheric.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget_Speed_Atmospheric.setObjectName("tableWidget_Speed_Atmospheric")
        self.tableWidget_Speed_Atmospheric.setColumnCount(0)
        self.tableWidget_Speed_Atmospheric.setRowCount(0)
        self.horizontalLayout_13.addWidget(self.tableWidget_Speed_Atmospheric)
        self.tabWidget_right.addTab(self.tab_PARA, "")
        self.tab_help = QtWidgets.QWidget()
        self.tab_help.setObjectName("tab_help")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_help)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textBrowser_Help = QtWidgets.QTextBrowser(self.tab_help)
        self.textBrowser_Help.setObjectName("textBrowser_Help")
        self.verticalLayout_6.addWidget(self.textBrowser_Help)
        self.tabWidget_right.addTab(self.tab_help, "")
        self.horizontalLayout_14.addWidget(self.tabWidget_right)
        self.actionAddRow = QtWidgets.QAction(FLTCON)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cardIco/rc_card/icos/AddedIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddRow.setIcon(icon)
        self.actionAddRow.setObjectName("actionAddRow")
        self.actionDeleteRow = QtWidgets.QAction(FLTCON)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/cardIco/rc_card/icos/DeletedIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteRow.setIcon(icon1)
        self.actionDeleteRow.setObjectName("actionDeleteRow")

        self.retranslateUi(FLTCON)
        self.comboBox_Variables.setCurrentIndex(1)
        self.tabWidget_right.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(FLTCON)

    def retranslateUi(self, FLTCON):
        _translate = QtCore.QCoreApplication.translate
        FLTCON.setWindowTitle(_translate("FLTCON", "飞行条件参数"))
        self.groupBox_flt.setTitle(_translate("FLTCON", "飞行条件"))
        self.label.setText(_translate("FLTCON", "LOOP 循环模式"))
        self.comboBox_LOOP.setItemText(0, _translate("FLTCON", "=1 同步计算高度、马赫数（默认值）"))
        self.comboBox_LOOP.setItemText(1, _translate("FLTCON", "=2 高度固定遍历马赫数"))
        self.comboBox_LOOP.setItemText(2, _translate("FLTCON", "=3 马赫数固定遍历高度"))
        self.label_2.setText(_translate("FLTCON", "变量组合 "))
        self.comboBox_Variables.setItemText(0, _translate("FLTCON", "马赫数 + 雷诺数 （NACA选项是必须）"))
        self.comboBox_Variables.setItemText(1, _translate("FLTCON", "马赫数 + 高度"))
        self.comboBox_Variables.setItemText(2, _translate("FLTCON", "自由流速度 + 高度"))
        self.comboBox_Variables.setItemText(3, _translate("FLTCON", "自由流静压 + 自由流温度 + 自由流速"))
        self.comboBox_Variables.setItemText(4, _translate("FLTCON", "自由流静压 + 自由流温度 + 马赫数"))
        self.checkBox_UsingNACA.setToolTip(_translate("FLTCON", "使用NACA控制卡的情况下，将强制输入马赫数和雷诺数"))
        self.checkBox_UsingNACA.setText(_translate("FLTCON", "使用NACA Control Card"))
        self.label_3.setText(_translate("FLTCON", "NMACH  马赫数"))
        self.label_5.setText(_translate("FLTCON", "NALT   大气条件个数"))
        self.label_4.setText(_translate("FLTCON", "NALPHA 攻角数"))
        self.groupBox_otherFlt.setTitle(_translate("FLTCON", "其他飞行条件"))
        self.checkBox_WT.setText(_translate("FLTCON", "WT    飞行器重量"))
        self.WT.setText(_translate("FLTCON", "1"))
        self.checkBox_GAMMA.setText(_translate("FLTCON", "GAMMA 飞行航迹角"))
        self.GAMMA.setText(_translate("FLTCON", "0"))
        self.groupBox_options.setTitle(_translate("FLTCON", "附加配置"))
        self.checkBox_STMACH.setText(_translate("FLTCON", "STMACH 亚音速上限"))
        self.STMACH.setText(_translate("FLTCON", "0.6"))
        self.checkBox_TSMACH.setText(_translate("FLTCON", "TSMACH 超音速下限"))
        self.TSMACH.setText(_translate("FLTCON", "1.4"))
        self.checkBox_HYPERS.setText(_translate("FLTCON", "HYPERS 超音速分析"))
        self.comboBox_HYPERS.setItemText(0, _translate("FLTCON", ".TRUE"))
        self.comboBox_HYPERS.setItemText(1, _translate("FLTCON", ".FALSE"))
        self.checkBox_TR.setText(_translate("FLTCON", "TR 效应分析"))
        self.comboBox_TR.setItemText(0, _translate("FLTCON", "1.0"))
        self.comboBox_TR.setItemText(1, _translate("FLTCON", "0.0"))
        self.tableWidget_ALSCHD.setToolTip(_translate("FLTCON", "录入攻角"))
        self.tabWidget_right.setTabText(self.tabWidget_right.indexOf(self.tab_PARA), _translate("FLTCON", "参数录入"))
        self.textBrowser_Help.setHtml(_translate("FLTCON", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Tips1:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">PINF </span>自由流静压  （分析Transverse-Jet Control时必须）详见TRNJET</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Tips2：</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Tips4：</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">变量组合 MACH RNNUB，必须配合使用 NACA CONTROL CARD</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Tips5：</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">如果在使用对应组合时输入了如下参数，这些参数将被优先使用</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MACH ALT       ： PINF TINF RNNUB</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">VINF ALT       ： PINF TINF MACH  RNNUB</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PINF TINF VINF ： RNNUB MACH  </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PINF TINF MACH ： RNNUB VINF</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">此处的参数都是可以输入的</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Tips6：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">atmospheric conditions are input as either altitude or pressure and temperature</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p></body></html>"))
        self.tabWidget_right.setTabText(self.tabWidget_right.indexOf(self.tab_help), _translate("FLTCON", "帮助"))
        self.actionAddRow.setText(_translate("FLTCON", "增加行"))
        self.actionAddRow.setToolTip(_translate("FLTCON", "新增行"))
        self.actionDeleteRow.setText(_translate("FLTCON", "删除行"))
        self.actionDeleteRow.setToolTip(_translate("FLTCON", "删除一行"))

import card_ico_rc
import card_rc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FLTCON = QtWidgets.QWidget()
    ui = Ui_FLTCON()
    ui.setupUi(FLTCON)
    FLTCON.show()
    sys.exit(app.exec_())

