# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\PlaneConfiguration\FLTCON.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(925, 528)
        self.tab3 = QtWidgets.QTableWidget(Form)
        self.tab3.setGeometry(QtCore.QRect(660, 30, 231, 481))
        self.tab3.setObjectName("tab3")
        self.tab3.setColumnCount(0)
        self.tab3.setRowCount(0)
        self.groupBox3 = QtWidgets.QGroupBox(Form)
        self.groupBox3.setGeometry(QtCore.QRect(10, 350, 371, 161))
        self.groupBox3.setObjectName("groupBox3")
        self.label_12 = QtWidgets.QLabel(self.groupBox3)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 71, 16))
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.groupBox3)
        self.label_11.setGeometry(QtCore.QRect(20, 100, 71, 16))
        self.label_11.setObjectName("label_11")
        self.label_6 = QtWidgets.QLabel(self.groupBox3)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label_6.setObjectName("label_6")
        self.Input_HyperS_UpperLimit = QtWidgets.QLineEdit(self.groupBox3)
        self.Input_HyperS_UpperLimit.setGeometry(QtCore.QRect(110, 60, 113, 20))
        self.Input_HyperS_UpperLimit.setObjectName("Input_HyperS_UpperLimit")
        self.label_10 = QtWidgets.QLabel(self.groupBox3)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 71, 16))
        self.label_10.setObjectName("label_10")
        self.comboBox_HYPERS = QtWidgets.QComboBox(self.groupBox3)
        self.comboBox_HYPERS.setGeometry(QtCore.QRect(110, 100, 111, 22))
        self.comboBox_HYPERS.setObjectName("comboBox_HYPERS")
        self.comboBox_HYPERS.addItem("")
        self.comboBox_HYPERS.addItem("")
        self.comboBox_TR = QtWidgets.QComboBox(self.groupBox3)
        self.comboBox_TR.setGeometry(QtCore.QRect(110, 130, 111, 22))
        self.comboBox_TR.setObjectName("comboBox_TR")
        self.comboBox_TR.addItem("")
        self.comboBox_TR.addItem("")
        self.Input_SubS_LowerLimit = QtWidgets.QLineEdit(self.groupBox3)
        self.Input_SubS_LowerLimit.setGeometry(QtCore.QRect(110, 30, 113, 20))
        self.Input_SubS_LowerLimit.setObjectName("Input_SubS_LowerLimit")
        self.tab2 = QtWidgets.QTableWidget(Form)
        self.tab2.setGeometry(QtCore.QRect(530, 30, 121, 481))
        self.tab2.setObjectName("tab2")
        self.tab2.setColumnCount(0)
        self.tab2.setRowCount(0)
        self.groupBox1 = QtWidgets.QGroupBox(Form)
        self.groupBox1.setGeometry(QtCore.QRect(10, 20, 371, 211))
        self.groupBox1.setObjectName("groupBox1")
        self.comboBox_Loop = QtWidgets.QComboBox(self.groupBox1)
        self.comboBox_Loop.setGeometry(QtCore.QRect(110, 30, 231, 22))
        self.comboBox_Loop.setObjectName("comboBox_Loop")
        self.comboBox_Loop.addItem("")
        self.comboBox_Loop.addItem("")
        self.comboBox_Loop.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox1)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 54, 12))
        self.label_4.setObjectName("label_4")
        self.comboBox_Variables = QtWidgets.QComboBox(self.groupBox1)
        self.comboBox_Variables.setGeometry(QtCore.QRect(110, 60, 231, 22))
        self.comboBox_Variables.setObjectName("comboBox_Variables")
        self.comboBox_Variables.addItem("")
        self.comboBox_Variables.addItem("")
        self.comboBox_Variables.addItem("")
        self.comboBox_Variables.addItem("")
        self.comboBox_Variables.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox1)
        self.label.setGeometry(QtCore.QRect(10, 30, 54, 12))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBox1)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox1)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox1)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 54, 12))
        self.label_5.setObjectName("label_5")
        self.checkBox_Atmosphere = QtWidgets.QCheckBox(self.groupBox1)
        self.checkBox_Atmosphere.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.checkBox_Atmosphere.setObjectName("checkBox_Atmosphere")
        self.spinBox_inputNMACH = QtWidgets.QSpinBox(self.groupBox1)
        self.spinBox_inputNMACH.setGeometry(QtCore.QRect(110, 120, 42, 22))
        self.spinBox_inputNMACH.setObjectName("spinBox_inputNMACH")
        self.spinBox_inputNALT = QtWidgets.QSpinBox(self.groupBox1)
        self.spinBox_inputNALT.setGeometry(QtCore.QRect(110, 180, 42, 22))
        self.spinBox_inputNALT.setObjectName("spinBox_inputNALT")
        self.spinBox_inputNALPHA = QtWidgets.QSpinBox(self.groupBox1)
        self.spinBox_inputNALPHA.setGeometry(QtCore.QRect(110, 150, 42, 22))
        self.spinBox_inputNALPHA.setObjectName("spinBox_inputNALPHA")
        self.groupBox2 = QtWidgets.QGroupBox(Form)
        self.groupBox2.setGeometry(QtCore.QRect(10, 240, 371, 91))
        self.groupBox2.setObjectName("groupBox2")
        self.inputFlightAngle = QtWidgets.QLineEdit(self.groupBox2)
        self.inputFlightAngle.setGeometry(QtCore.QRect(130, 60, 113, 20))
        self.inputFlightAngle.setObjectName("inputFlightAngle")
        self.inputFlightWeight = QtWidgets.QLineEdit(self.groupBox2)
        self.inputFlightWeight.setGeometry(QtCore.QRect(130, 30, 113, 20))
        self.inputFlightWeight.setObjectName("inputFlightWeight")
        self.checkBox_FlightWeight = QtWidgets.QCheckBox(self.groupBox2)
        self.checkBox_FlightWeight.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.checkBox_FlightWeight.setObjectName("checkBox_FlightWeight")
        self.checkBox_FlightPathAngle = QtWidgets.QCheckBox(self.groupBox2)
        self.checkBox_FlightPathAngle.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.checkBox_FlightPathAngle.setObjectName("checkBox_FlightPathAngle")
        self.tab1 = QtWidgets.QTableWidget(Form)
        self.tab1.setGeometry(QtCore.QRect(400, 30, 121, 481))
        self.tab1.setObjectName("tab1")
        self.tab1.setColumnCount(0)
        self.tab1.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox3.setTitle(_translate("Form", "附加配置"))
        self.label_12.setText(_translate("Form", "TR效应分析"))
        self.label_11.setText(_translate("Form", "超音速分析"))
        self.label_6.setText(_translate("Form", "亚音速上限"))
        self.Input_HyperS_UpperLimit.setText(_translate("Form", "1.4"))
        self.label_10.setText(_translate("Form", "超音速下限"))
        self.comboBox_HYPERS.setItemText(0, _translate("Form", ".TRUE"))
        self.comboBox_HYPERS.setItemText(1, _translate("Form", ".FALSE"))
        self.comboBox_TR.setItemText(0, _translate("Form", "1.0"))
        self.comboBox_TR.setItemText(1, _translate("Form", "0.0"))
        self.Input_SubS_LowerLimit.setText(_translate("Form", "0.6"))
        self.groupBox1.setTitle(_translate("Form", "飞行条件"))
        self.comboBox_Loop.setItemText(0, _translate("Form", "=1 同步计算高度、马赫数（默认值）"))
        self.comboBox_Loop.setItemText(1, _translate("Form", "=2 高度固定遍历马赫数"))
        self.comboBox_Loop.setItemText(2, _translate("Form", "=3 马赫数固定遍历高度"))
        self.label_4.setText(_translate("Form", "攻角数："))
        self.comboBox_Variables.setItemText(0, _translate("Form", "马赫数 + 雷诺数 （NACA选项是必须）"))
        self.comboBox_Variables.setItemText(1, _translate("Form", "马赫数 + 高度"))
        self.comboBox_Variables.setItemText(2, _translate("Form", "自由流速度 + 高度"))
        self.comboBox_Variables.setItemText(3, _translate("Form", "自由流静压 + 自由流温度 + 自由流速"))
        self.comboBox_Variables.setItemText(4, _translate("Form", "自由流静压 + 自由流温度 + 马赫数"))
        self.label.setText(_translate("Form", "循环模式："))
        self.label_3.setText(_translate("Form", "马赫数："))
        self.label_2.setText(_translate("Form", "变量组合："))
        self.label_5.setText(_translate("Form", "高度数："))
        self.checkBox_Atmosphere.setText(_translate("Form", "使用标准大气"))
        self.groupBox2.setTitle(_translate("Form", "其他飞行条件"))
        self.inputFlightAngle.setText(_translate("Form", "0"))
        self.inputFlightWeight.setText(_translate("Form", "1"))
        self.checkBox_FlightWeight.setText(_translate("Form", "飞行器重量"))
        self.checkBox_FlightPathAngle.setText(_translate("Form", "飞行航迹角"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

