# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\PlaneConfiguration\HTPLNF.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1055, 705)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 30, 61, 32))
        self.label.setObjectName("label")
        self.lineEdit_CHRDTP = QtWidgets.QLineEdit(Form)
        self.lineEdit_CHRDTP.setGeometry(QtCore.QRect(260, 120, 133, 20))
        self.lineEdit_CHRDTP.setObjectName("lineEdit_CHRDTP")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(50, 522, 180, 35))
        self.label_12.setObjectName("label_12")
        self.lineEdit_TWISTA = QtWidgets.QLineEdit(Form)
        self.lineEdit_TWISTA.setGeometry(QtCore.QRect(260, 490, 133, 20))
        self.lineEdit_TWISTA.setObjectName("lineEdit_TWISTA")
        self.lineEdit_CHRDR = QtWidgets.QLineEdit(Form)
        self.lineEdit_CHRDR.setGeometry(QtCore.QRect(260, 320, 133, 20))
        self.lineEdit_CHRDR.setObjectName("lineEdit_CHRDR")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 233, 180, 36))
        self.label_5.setObjectName("label_5")
        self.comboBox_WShape = QtWidgets.QComboBox(Form)
        self.comboBox_WShape.setGeometry(QtCore.QRect(150, 40, 181, 22))
        self.comboBox_WShape.setObjectName("comboBox_WShape")
        self.comboBox_WShape.addItem("")
        self.comboBox_WShape.addItem("")
        self.comboBox_WShape.addItem("")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(50, 563, 180, 35))
        self.label_13.setObjectName("label_13")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 180, 35))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 151, 180, 35))
        self.label_3.setObjectName("label_3")
        self.label_SAVSO = QtWidgets.QLabel(Form)
        self.label_SAVSO.setGeometry(QtCore.QRect(50, 398, 180, 35))
        self.label_SAVSO.setObjectName("label_SAVSO")
        self.lineEdit_DHDADI = QtWidgets.QLineEdit(Form)
        self.lineEdit_DHDADI.setGeometry(QtCore.QRect(260, 570, 133, 20))
        self.lineEdit_DHDADI.setObjectName("lineEdit_DHDADI")
        self.lineEdit_SSPN = QtWidgets.QLineEdit(Form)
        self.lineEdit_SSPN.setGeometry(QtCore.QRect(260, 240, 133, 20))
        self.lineEdit_SSPN.setObjectName("lineEdit_SSPN")
        self.lineEdit_DHDADO = QtWidgets.QLineEdit(Form)
        self.lineEdit_DHDADO.setGeometry(QtCore.QRect(260, 610, 133, 20))
        self.lineEdit_DHDADO.setObjectName("lineEdit_DHDADO")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(50, 316, 180, 35))
        self.label_7.setObjectName("label_7")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(480, 350, 500, 300))
        self.label_16.setObjectName("label_16")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(50, 275, 180, 35))
        self.label_6.setObjectName("label_6")
        self.image_HTPLNF = QtWidgets.QLabel(Form)
        self.image_HTPLNF.setGeometry(QtCore.QRect(490, 30, 500, 300))
        self.image_HTPLNF.setObjectName("image_HTPLNF")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(50, 480, 180, 36))
        self.label_11.setObjectName("label_11")
        self.lineEdit_SSPNE = QtWidgets.QLineEdit(Form)
        self.lineEdit_SSPNE.setGeometry(QtCore.QRect(260, 200, 133, 20))
        self.lineEdit_SSPNE.setObjectName("lineEdit_SSPNE")
        self.lineEdit_SAVSO = QtWidgets.QLineEdit(Form)
        self.lineEdit_SAVSO.setGeometry(QtCore.QRect(260, 410, 133, 20))
        self.lineEdit_SAVSO.setObjectName("lineEdit_SAVSO")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(50, 604, 180, 35))
        self.label_14.setObjectName("label_14")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(50, 357, 180, 35))
        self.label_8.setObjectName("label_8")
        self.lineEdit_CHRDBP = QtWidgets.QLineEdit(Form)
        self.lineEdit_CHRDBP.setGeometry(QtCore.QRect(260, 280, 133, 20))
        self.lineEdit_CHRDBP.setObjectName("lineEdit_CHRDBP")
        self.lineEdit_SSPNOP = QtWidgets.QLineEdit(Form)
        self.lineEdit_SSPNOP.setGeometry(QtCore.QRect(260, 160, 133, 20))
        self.lineEdit_SSPNOP.setObjectName("lineEdit_SSPNOP")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(50, 439, 180, 35))
        self.label_10.setObjectName("label_10")
        self.lineEdit_CHSTAT = QtWidgets.QLineEdit(Form)
        self.lineEdit_CHSTAT.setGeometry(QtCore.QRect(260, 450, 133, 20))
        self.lineEdit_CHSTAT.setObjectName("lineEdit_CHSTAT")
        self.lineEdit_SAVSI = QtWidgets.QLineEdit(Form)
        self.lineEdit_SAVSI.setGeometry(QtCore.QRect(260, 370, 133, 20))
        self.lineEdit_SAVSI.setObjectName("lineEdit_SAVSI")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 192, 180, 35))
        self.label_4.setObjectName("label_4")
        self.lineEdit_SSPNDD = QtWidgets.QLineEdit(Form)
        self.lineEdit_SSPNDD.setGeometry(QtCore.QRect(260, 532, 133, 20))
        self.lineEdit_SSPNDD.setObjectName("lineEdit_SSPNDD")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(50, 80, 180, 35))
        self.label_15.setObjectName("label_15")
        self.lineEdit_MACHN = QtWidgets.QLineEdit(Form)
        self.lineEdit_MACHN.setGeometry(QtCore.QRect(260, 90, 133, 20))
        self.lineEdit_MACHN.setObjectName("lineEdit_MACHN")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "机翼类型"))
        self.label_12.setText(_translate("Form", "SSPNDD：内上反角的外侧板半展长"))
        self.label_5.setText(_translate("Form", "SSPN：理论根弦的理论半展长"))
        self.comboBox_WShape.setItemText(0, _translate("Form", "1.0 直锥型外形"))
        self.comboBox_WShape.setItemText(1, _translate("Form", "2.0 双三角翼型外形（展现比≤3）"))
        self.comboBox_WShape.setItemText(2, _translate("Form", "3.0 边条型外形（展弦比≤3）"))
        self.label_13.setText(_translate("Form", "DHDADI：内侧板上反角"))
        self.label_2.setText(_translate("Form", "CHRDTP：稍弦长"))
        self.label_3.setText(_translate("Form", "SSPNOP：外侧板半展长"))
        self.label_SAVSO.setText(_translate("Form", "SAVSO：外侧板掠角"))
        self.label_7.setText(_translate("Form", "CHRDR：根弦长"))
        self.label_16.setText(_translate("Form", "TextLabel"))
        self.label_6.setText(_translate("Form", "CHRDBP：断点弦长"))
        self.image_HTPLNF.setText(_translate("Form", "TextLabel"))
        self.label_11.setText(_translate("Form", "TWISTA：扭转角"))
        self.label_14.setText(_translate("Form", "DHDADO：外侧板上反角"))
        self.label_8.setText(_translate("Form", "SAVSI：内侧板掠角"))
        self.label_10.setText(_translate("Form", "CHSTAT：内外侧板掠角的参考弦点"))
        self.label_4.setText(_translate("Form", "SSPNE：外露板半展长"))
        self.label_15.setText(_translate("Form", "马赫数（与飞行页一致）"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

