# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\PlaneConfiguration\HTPLNF.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HTPLNF(object):
    def setupUi(self, HTPLNF):
        HTPLNF.setObjectName("HTPLNF")
        HTPLNF.resize(1055, 527)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(HTPLNF)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(HTPLNF)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.comboBox_TYPE = QtWidgets.QComboBox(HTPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_TYPE.sizePolicy().hasHeightForWidth())
        self.comboBox_TYPE.setSizePolicy(sizePolicy)
        self.comboBox_TYPE.setObjectName("comboBox_TYPE")
        self.comboBox_TYPE.addItem("")
        self.comboBox_TYPE.addItem("")
        self.comboBox_TYPE.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_TYPE)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_CHRDTP = QtWidgets.QLabel(HTPLNF)
        self.label_CHRDTP.setObjectName("label_CHRDTP")
        self.horizontalLayout.addWidget(self.label_CHRDTP)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.CHRDTP = QtWidgets.QLineEdit(HTPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CHRDTP.sizePolicy().hasHeightForWidth())
        self.CHRDTP.setSizePolicy(sizePolicy)
        self.CHRDTP.setObjectName("CHRDTP")
        self.horizontalLayout.addWidget(self.CHRDTP)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_CHRDBP = QtWidgets.QLabel(HTPLNF)
        self.label_CHRDBP.setObjectName("label_CHRDBP")
        self.horizontalLayout_5.addWidget(self.label_CHRDBP)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.CHRDBP = QtWidgets.QLineEdit(HTPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CHRDBP.sizePolicy().hasHeightForWidth())
        self.CHRDBP.setSizePolicy(sizePolicy)
        self.CHRDBP.setObjectName("CHRDBP")
        self.horizontalLayout_5.addWidget(self.CHRDBP)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_CHRDR = QtWidgets.QLabel(HTPLNF)
        self.label_CHRDR.setObjectName("label_CHRDR")
        self.horizontalLayout_6.addWidget(self.label_CHRDR)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.CHRDR = QtWidgets.QLineEdit(HTPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CHRDR.sizePolicy().hasHeightForWidth())
        self.CHRDR.setSizePolicy(sizePolicy)
        self.CHRDR.setObjectName("CHRDR")
        self.horizontalLayout_6.addWidget(self.CHRDR)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_SSPNOP = QtWidgets.QLabel(HTPLNF)
        self.label_SSPNOP.setObjectName("label_SSPNOP")
        self.horizontalLayout_2.addWidget(self.label_SSPNOP)
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.SSPNOP = QtWidgets.QLineEdit(HTPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SSPNOP.sizePolicy().hasHeightForWidth())
        self.SSPNOP.setSizePolicy(sizePolicy)
        self.SSPNOP.setObjectName("SSPNOP")
        self.horizontalLayout_2.addWidget(self.SSPNOP)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_SSPNE = QtWidgets.QLabel(HTPLNF)
        self.label_SSPNE.setObjectName("label_SSPNE")
        self.horizontalLayout_3.addWidget(self.label_SSPNE)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.SSPNE = QtWidgets.QLineEdit(HTPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SSPNE.sizePolicy().hasHeightForWidth())
        self.SSPNE.setSizePolicy(sizePolicy)
        self.SSPNE.setObjectName("SSPNE")
        self.horizontalLayout_3.addWidget(self.SSPNE)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_SSPN = QtWidgets.QLabel(HTPLNF)
        self.label_SSPN.setObjectName("label_SSPN")
        self.horizontalLayout_4.addWidget(self.label_SSPN)
        spacerItem6 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.SSPN = QtWidgets.QLineEdit(HTPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SSPN.sizePolicy().hasHeightForWidth())
        self.SSPN.setSizePolicy(sizePolicy)
        self.SSPN.setObjectName("SSPN")
        self.horizontalLayout_4.addWidget(self.SSPN)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_SAVSI = QtWidgets.QLabel(HTPLNF)
        self.label_SAVSI.setObjectName("label_SAVSI")
        self.horizontalLayout_7.addWidget(self.label_SAVSI)
        spacerItem7 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.SAVSI = QtWidgets.QLineEdit(HTPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SAVSI.sizePolicy().hasHeightForWidth())
        self.SAVSI.setSizePolicy(sizePolicy)
        self.SAVSI.setObjectName("SAVSI")
        self.horizontalLayout_7.addWidget(self.SAVSI)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_SAVSO = QtWidgets.QLabel(HTPLNF)
        self.label_SAVSO.setObjectName("label_SAVSO")
        self.horizontalLayout_8.addWidget(self.label_SAVSO)
        spacerItem8 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.SAVSO = QtWidgets.QLineEdit(HTPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SAVSO.sizePolicy().hasHeightForWidth())
        self.SAVSO.setSizePolicy(sizePolicy)
        self.SAVSO.setObjectName("SAVSO")
        self.horizontalLayout_8.addWidget(self.SAVSO)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_TWISTA = QtWidgets.QLabel(HTPLNF)
        self.label_TWISTA.setObjectName("label_TWISTA")
        self.horizontalLayout_10.addWidget(self.label_TWISTA)
        spacerItem9 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.TWISTA = QtWidgets.QLineEdit(HTPLNF)
        self.TWISTA.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TWISTA.sizePolicy().hasHeightForWidth())
        self.TWISTA.setSizePolicy(sizePolicy)
        self.TWISTA.setObjectName("TWISTA")
        self.horizontalLayout_10.addWidget(self.TWISTA)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_CHSTAT = QtWidgets.QLabel(HTPLNF)
        self.label_CHSTAT.setObjectName("label_CHSTAT")
        self.horizontalLayout_9.addWidget(self.label_CHSTAT)
        spacerItem10 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.CHSTAT = QtWidgets.QLineEdit(HTPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CHSTAT.sizePolicy().hasHeightForWidth())
        self.CHSTAT.setSizePolicy(sizePolicy)
        self.CHSTAT.setObjectName("CHSTAT")
        self.horizontalLayout_9.addWidget(self.CHSTAT)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_SSPNDD = QtWidgets.QLabel(HTPLNF)
        self.label_SSPNDD.setObjectName("label_SSPNDD")
        self.horizontalLayout_11.addWidget(self.label_SSPNDD)
        spacerItem11 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.SSPNDD = QtWidgets.QLineEdit(HTPLNF)
        self.SSPNDD.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SSPNDD.sizePolicy().hasHeightForWidth())
        self.SSPNDD.setSizePolicy(sizePolicy)
        self.SSPNDD.setObjectName("SSPNDD")
        self.horizontalLayout_11.addWidget(self.SSPNDD)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_DHDADI = QtWidgets.QLabel(HTPLNF)
        self.label_DHDADI.setObjectName("label_DHDADI")
        self.horizontalLayout_12.addWidget(self.label_DHDADI)
        spacerItem12 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem12)
        self.DHDADI = QtWidgets.QLineEdit(HTPLNF)
        self.DHDADI.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DHDADI.sizePolicy().hasHeightForWidth())
        self.DHDADI.setSizePolicy(sizePolicy)
        self.DHDADI.setObjectName("DHDADI")
        self.horizontalLayout_12.addWidget(self.DHDADI)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_DHDADO = QtWidgets.QLabel(HTPLNF)
        self.label_DHDADO.setObjectName("label_DHDADO")
        self.horizontalLayout_13.addWidget(self.label_DHDADO)
        spacerItem13 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.DHDADO = QtWidgets.QLineEdit(HTPLNF)
        self.DHDADO.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DHDADO.sizePolicy().hasHeightForWidth())
        self.DHDADO.setSizePolicy(sizePolicy)
        self.DHDADO.setObjectName("DHDADO")
        self.horizontalLayout_13.addWidget(self.DHDADO)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        self.horizontalLayout_15.addLayout(self.verticalLayout)
        self.tabWidget = QtWidgets.QTabWidget(HTPLNF)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_coefficient = QtWidgets.QWidget()
        self.tab_coefficient.setObjectName("tab_coefficient")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.tab_coefficient)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.tableWidget_HTArea = QtWidgets.QTableWidget(self.tab_coefficient)
        self.tableWidget_HTArea.setObjectName("tableWidget_HTArea")
        self.tableWidget_HTArea.setColumnCount(0)
        self.tableWidget_HTArea.setRowCount(0)
        self.horizontalLayout_19.addWidget(self.tableWidget_HTArea)
        self.tabWidget.addTab(self.tab_coefficient, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_16.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout_15.addWidget(self.tabWidget)

        self.retranslateUi(HTPLNF)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HTPLNF)

    def retranslateUi(self, HTPLNF):
        _translate = QtCore.QCoreApplication.translate
        HTPLNF.setWindowTitle(_translate("HTPLNF", "平尾参数"))
        self.label.setText(_translate("HTPLNF", "机翼类型"))
        self.comboBox_TYPE.setItemText(0, _translate("HTPLNF", "1.0 直锥型外形"))
        self.comboBox_TYPE.setItemText(1, _translate("HTPLNF", "2.0 双三角翼型外形（展弦比≤3）"))
        self.comboBox_TYPE.setItemText(2, _translate("HTPLNF", "3.0 边条型外形（展弦比≤3）"))
        self.label_CHRDTP.setText(_translate("HTPLNF", "CHRDTP：稍弦长"))
        self.label_CHRDBP.setText(_translate("HTPLNF", "CHRDBP：断点弦长"))
        self.label_CHRDR.setText(_translate("HTPLNF", "CHRDR：根弦长"))
        self.label_SSPNOP.setText(_translate("HTPLNF", "SSPNOP：外侧板半展长"))
        self.label_SSPNE.setText(_translate("HTPLNF", "SSPNE：外露板半展长"))
        self.label_SSPN.setText(_translate("HTPLNF", "SSPN：理论根弦的理论半展长"))
        self.label_SAVSI.setText(_translate("HTPLNF", "SAVSI：内侧板掠角"))
        self.label_SAVSO.setText(_translate("HTPLNF", "SAVSO：外侧板掠角"))
        self.label_TWISTA.setText(_translate("HTPLNF", "TWISTA：扭转角"))
        self.label_CHSTAT.setText(_translate("HTPLNF", "CHSTAT：内外侧板掠角的参考弦点"))
        self.label_SSPNDD.setText(_translate("HTPLNF", "SSPNDD：内上反角的外侧板半展长"))
        self.label_DHDADI.setText(_translate("HTPLNF", "DHDADI：内侧板上反角"))
        self.label_DHDADO.setText(_translate("HTPLNF", "DHDADO：外侧板上反角"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_coefficient), _translate("HTPLNF", "平尾受机翼影响"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("HTPLNF", "说明"))

import card_rc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HTPLNF = QtWidgets.QWidget()
    ui = Ui_HTPLNF()
    ui.setupUi(HTPLNF)
    HTPLNF.show()
    sys.exit(app.exec_())

