# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\PlaneConfiguration\SYNTHS.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(885, 647)
        self.checkBox_HINAX = QtWidgets.QCheckBox(Form)
        self.checkBox_HINAX.setGeometry(QtCore.QRect(10, 340, 201, 16))
        self.checkBox_HINAX.setObjectName("checkBox_HINAX")
        self.ALIW = QtWidgets.QLineEdit(Form)
        self.ALIW.setGeometry(QtCore.QRect(250, 180, 133, 20))
        self.ALIW.setObjectName("ALIW")
        self.HINAX = QtWidgets.QLineEdit(Form)
        self.HINAX.setGeometry(QtCore.QRect(250, 340, 133, 20))
        self.HINAX.setObjectName("HINAX")
        self.XW = QtWidgets.QLineEdit(Form)
        self.XW.setGeometry(QtCore.QRect(250, 90, 133, 20))
        self.XW.setObjectName("XW")
        self.ZCG = QtWidgets.QLineEdit(Form)
        self.ZCG.setGeometry(QtCore.QRect(250, 50, 133, 20))
        self.ZCG.setObjectName("ZCG")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(30, 370, 191, 36))
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 85, 181, 36))
        self.label_3.setObjectName("label_3")
        self.ZV = QtWidgets.QLineEdit(Form)
        self.ZV.setGeometry(QtCore.QRect(250, 420, 133, 20))
        self.ZV.setObjectName("ZV")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(30, 410, 181, 35))
        self.label_10.setObjectName("label_10")
        self.XH = QtWidgets.QLineEdit(Form)
        self.XH.setGeometry(QtCore.QRect(250, 220, 133, 20))
        self.XH.setObjectName("XH")
        self.ZW = QtWidgets.QLineEdit(Form)
        self.ZW.setGeometry(QtCore.QRect(250, 130, 133, 20))
        self.ZW.setObjectName("ZW")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 293, 131, 36))
        self.label_8.setObjectName("label_8")
        self.ALIH = QtWidgets.QLineEdit(Form)
        self.ALIH.setGeometry(QtCore.QRect(250, 300, 133, 20))
        self.ALIH.setObjectName("ALIH")
        self.pictureSYNTHS = QtWidgets.QLabel(Form)
        self.pictureSYNTHS.setGeometry(QtCore.QRect(460, 20, 500, 400))
        self.pictureSYNTHS.setObjectName("pictureSYNTHS")
        self.ZVF = QtWidgets.QLineEdit(Form)
        self.ZVF.setGeometry(QtCore.QRect(250, 500, 133, 20))
        self.ZVF.setObjectName("ZVF")
        self.ZH = QtWidgets.QLineEdit(Form)
        self.ZH.setGeometry(QtCore.QRect(250, 260, 133, 20))
        self.ZH.setObjectName("ZH")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(460, 430, 501, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(30, 450, 191, 36))
        self.label_11.setObjectName("label_11")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 169, 121, 35))
        self.label_5.setObjectName("label_5")
        self.SCALE = QtWidgets.QLineEdit(Form)
        self.SCALE.setGeometry(QtCore.QRect(250, 570, 133, 20))
        self.SCALE.setObjectName("SCALE")
        self.XVF = QtWidgets.QLineEdit(Form)
        self.XVF.setGeometry(QtCore.QRect(250, 460, 133, 20))
        self.XVF.setObjectName("XVF")
        self.VERTUP = QtWidgets.QComboBox(Form)
        self.VERTUP.setGeometry(QtCore.QRect(250, 540, 133, 20))
        self.VERTUP.setMouseTracking(False)
        self.VERTUP.setAutoFillBackground(False)
        self.VERTUP.setObjectName("VERTUP")
        self.VERTUP.addItem("")
        self.VERTUP.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 2, 121, 36))
        self.label.setObjectName("label")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(30, 490, 191, 36))
        self.label_12.setObjectName("label_12")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 252, 171, 35))
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 127, 181, 36))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 44, 131, 35))
        self.label_2.setObjectName("label_2")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(30, 565, 131, 36))
        self.label_14.setObjectName("label_14")
        self.XV = QtWidgets.QLineEdit(Form)
        self.XV.setGeometry(QtCore.QRect(250, 380, 133, 20))
        self.XV.setObjectName("XV")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(30, 524, 181, 35))
        self.label_13.setObjectName("label_13")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 210, 181, 36))
        self.label_6.setObjectName("label_6")
        self.XCG = QtWidgets.QLineEdit(Form)
        self.XCG.setGeometry(QtCore.QRect(250, 10, 133, 20))
        self.XCG.setObjectName("XCG")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_HINAX.setText(_translate("Form", "HINAX：平尾铰链轴的纵向位置"))
        self.label_9.setText(_translate("Form", "XV  ：垂尾理论顶端的纵向位置"))
        self.label_3.setText(_translate("Form", "XW  ：机翼理论顶端的纵向位置"))
        self.label_10.setText(_translate("Form", "ZV  ：垂尾理论顶端的垂向位置"))
        self.label_8.setText(_translate("Form", "ALIH：平尾安装角"))
        self.pictureSYNTHS.setText(_translate("Form", "TextLabel"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. HINAX只针对全动平尾布局</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. 输入HINAX时，XH和ZH被认为是0安装角（iw=0）</p></body></html>"))
        self.label_11.setText(_translate("Form", "XVF ：腹鳍理论顶端的纵向位置"))
        self.label_5.setText(_translate("Form", "ALIW：机翼安装角"))
        self.VERTUP.setItemText(0, _translate("Form", ".true表示垂直板在参考面上方（系统默认）"))
        self.VERTUP.setItemText(1, _translate("Form", ".false表示垂直板在参考面下方"))
        self.label.setText(_translate("Form", "XCG ：重心纵向位置"))
        self.label_12.setText(_translate("Form", "ZVF ：腹鳍理论顶端的垂向位置"))
        self.label_7.setText(_translate("Form", "ZH  ：平尾理论顶端的纵向位置"))
        self.label_4.setText(_translate("Form", "ZW  ：机翼理论顶端的垂向位置"))
        self.label_2.setText(_translate("Form", "ZCG ：重心垂向位置"))
        self.label_14.setText(_translate("Form", "SCALE：缩放因子"))
        self.label_13.setText(_translate("Form", "VERTUP：腹鳍与参考面位置关系"))
        self.label_6.setText(_translate("Form", "XH  ：平尾理论顶端的纵向位置"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

