# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\PlaneConfiguration\VFPLNF.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VFPLNF(object):
    def setupUi(self, VFPLNF):
        VFPLNF.setObjectName("VFPLNF")
        VFPLNF.resize(1054, 496)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(VFPLNF)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(VFPLNF)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.comboBox_TYPE = QtWidgets.QComboBox(VFPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_TYPE.sizePolicy().hasHeightForWidth())
        self.comboBox_TYPE.setSizePolicy(sizePolicy)
        self.comboBox_TYPE.setObjectName("comboBox_TYPE")
        self.comboBox_TYPE.addItem("")
        self.comboBox_TYPE.addItem("")
        self.comboBox_TYPE.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_TYPE)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(VFPLNF)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.CHRDTP = QtWidgets.QLineEdit(VFPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CHRDTP.sizePolicy().hasHeightForWidth())
        self.CHRDTP.setSizePolicy(sizePolicy)
        self.CHRDTP.setObjectName("CHRDTP")
        self.horizontalLayout.addWidget(self.CHRDTP)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(VFPLNF)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.CHRDBP = QtWidgets.QLineEdit(VFPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CHRDBP.sizePolicy().hasHeightForWidth())
        self.CHRDBP.setSizePolicy(sizePolicy)
        self.CHRDBP.setObjectName("CHRDBP")
        self.horizontalLayout_5.addWidget(self.CHRDBP)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(VFPLNF)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.CHRDR = QtWidgets.QLineEdit(VFPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CHRDR.sizePolicy().hasHeightForWidth())
        self.CHRDR.setSizePolicy(sizePolicy)
        self.CHRDR.setObjectName("CHRDR")
        self.horizontalLayout_6.addWidget(self.CHRDR)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(VFPLNF)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.SSPNOP = QtWidgets.QLineEdit(VFPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SSPNOP.sizePolicy().hasHeightForWidth())
        self.SSPNOP.setSizePolicy(sizePolicy)
        self.SSPNOP.setObjectName("SSPNOP")
        self.horizontalLayout_2.addWidget(self.SSPNOP)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(VFPLNF)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.SSPNE = QtWidgets.QLineEdit(VFPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SSPNE.sizePolicy().hasHeightForWidth())
        self.SSPNE.setSizePolicy(sizePolicy)
        self.SSPNE.setObjectName("SSPNE")
        self.horizontalLayout_3.addWidget(self.SSPNE)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(VFPLNF)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem6 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.SSPN = QtWidgets.QLineEdit(VFPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SSPN.sizePolicy().hasHeightForWidth())
        self.SSPN.setSizePolicy(sizePolicy)
        self.SSPN.setObjectName("SSPN")
        self.horizontalLayout_4.addWidget(self.SSPN)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(VFPLNF)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        spacerItem7 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.SAVSI = QtWidgets.QLineEdit(VFPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SAVSI.sizePolicy().hasHeightForWidth())
        self.SAVSI.setSizePolicy(sizePolicy)
        self.SAVSI.setObjectName("SAVSI")
        self.horizontalLayout_7.addWidget(self.SAVSI)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_SAVSO = QtWidgets.QLabel(VFPLNF)
        self.label_SAVSO.setObjectName("label_SAVSO")
        self.horizontalLayout_8.addWidget(self.label_SAVSO)
        spacerItem8 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.SAVSO = QtWidgets.QLineEdit(VFPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SAVSO.sizePolicy().hasHeightForWidth())
        self.SAVSO.setSizePolicy(sizePolicy)
        self.SAVSO.setObjectName("SAVSO")
        self.horizontalLayout_8.addWidget(self.SAVSO)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(VFPLNF)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        spacerItem9 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.TWISTA = QtWidgets.QLineEdit(VFPLNF)
        self.TWISTA.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TWISTA.sizePolicy().hasHeightForWidth())
        self.TWISTA.setSizePolicy(sizePolicy)
        self.TWISTA.setObjectName("TWISTA")
        self.horizontalLayout_10.addWidget(self.TWISTA)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(VFPLNF)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        spacerItem10 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.CHSTAT = QtWidgets.QLineEdit(VFPLNF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CHSTAT.sizePolicy().hasHeightForWidth())
        self.CHSTAT.setSizePolicy(sizePolicy)
        self.CHSTAT.setObjectName("CHSTAT")
        self.horizontalLayout_9.addWidget(self.CHSTAT)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(VFPLNF)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        spacerItem11 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.SSPNDD = QtWidgets.QLineEdit(VFPLNF)
        self.SSPNDD.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SSPNDD.sizePolicy().hasHeightForWidth())
        self.SSPNDD.setSizePolicy(sizePolicy)
        self.SSPNDD.setObjectName("SSPNDD")
        self.horizontalLayout_11.addWidget(self.SSPNDD)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(VFPLNF)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        spacerItem12 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem12)
        self.DHDADI = QtWidgets.QLineEdit(VFPLNF)
        self.DHDADI.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DHDADI.sizePolicy().hasHeightForWidth())
        self.DHDADI.setSizePolicy(sizePolicy)
        self.DHDADI.setObjectName("DHDADI")
        self.horizontalLayout_12.addWidget(self.DHDADI)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(VFPLNF)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        spacerItem13 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.DHDADO = QtWidgets.QLineEdit(VFPLNF)
        self.DHDADO.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DHDADO.sizePolicy().hasHeightForWidth())
        self.DHDADO.setSizePolicy(sizePolicy)
        self.DHDADO.setObjectName("DHDADO")
        self.horizontalLayout_13.addWidget(self.DHDADO)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15.addLayout(self.verticalLayout)
        self.tabWidget = QtWidgets.QTabWidget(VFPLNF)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_coefficient = QtWidgets.QWidget()
        self.tab_coefficient.setObjectName("tab_coefficient")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.tab_coefficient)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.tableWidget_VTArea = QtWidgets.QTableWidget(self.tab_coefficient)
        self.tableWidget_VTArea.setObjectName("tableWidget_VTArea")
        self.tableWidget_VTArea.setColumnCount(0)
        self.tableWidget_VTArea.setRowCount(0)
        self.horizontalLayout_19.addWidget(self.tableWidget_VTArea)
        self.tabWidget.addTab(self.tab_coefficient, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_16.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/card/rc_card/WGPLNF.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_17.addWidget(self.label_9)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/card/rc_card/WGPLNF_Para.png"))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_18.addWidget(self.label_15)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_15.addWidget(self.tabWidget)

        self.retranslateUi(VFPLNF)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VFPLNF)

    def retranslateUi(self, VFPLNF):
        _translate = QtCore.QCoreApplication.translate
        VFPLNF.setWindowTitle(_translate("VFPLNF", "腹鳍几何参数"))
        self.label.setText(_translate("VFPLNF", "机翼类型"))
        self.comboBox_TYPE.setItemText(0, _translate("VFPLNF", "1.0 直锥型外形"))
        self.comboBox_TYPE.setItemText(1, _translate("VFPLNF", "2.0 双三角翼型外形（展弦比≤3）"))
        self.comboBox_TYPE.setItemText(2, _translate("VFPLNF", "3.0 边条型外形（展弦比≤3）"))
        self.label_2.setText(_translate("VFPLNF", "CHRDTP：稍弦长"))
        self.label_6.setText(_translate("VFPLNF", "CHRDBP：断点弦长"))
        self.label_7.setText(_translate("VFPLNF", "CHRDR：根弦长"))
        self.label_3.setText(_translate("VFPLNF", "SSPNOP：外侧板半展长"))
        self.label_4.setText(_translate("VFPLNF", "SSPNE：外露板半展长"))
        self.label_5.setText(_translate("VFPLNF", "SSPN：理论根弦的理论半展长"))
        self.label_8.setText(_translate("VFPLNF", "SAVSI：内侧板掠角"))
        self.label_SAVSO.setText(_translate("VFPLNF", "SAVSO：外侧板掠角"))
        self.label_11.setText(_translate("VFPLNF", "TWISTA：扭转角"))
        self.label_10.setText(_translate("VFPLNF", "CHSTAT：内外侧板掠角的参考弦点"))
        self.label_12.setText(_translate("VFPLNF", "SSPNDD：内上反角的外侧板半展长"))
        self.label_13.setText(_translate("VFPLNF", "DHDADI：内侧板上反角"))
        self.label_14.setText(_translate("VFPLNF", "DHDADO：外侧板上反角"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_coefficient), _translate("VFPLNF", "腹鳍受机翼和平尾的影响"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("VFPLNF", "说明"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("VFPLNF", "示意图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("VFPLNF", "页"))

import card_rc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VFPLNF = QtWidgets.QWidget()
    ui = Ui_VFPLNF()
    ui.setupUi(VFPLNF)
    VFPLNF.show()
    sys.exit(app.exec_())

