# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab/GUIs/PlaneConfiguration/VTSCHR.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VTSCHR(object):
    def setupUi(self, VTSCHR):
        VTSCHR.setObjectName("VTSCHR")
        VTSCHR.resize(1012, 574)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(VTSCHR)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(VTSCHR)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.TOVC = QtWidgets.QLineEdit(VTSCHR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TOVC.sizePolicy().hasHeightForWidth())
        self.TOVC.setSizePolicy(sizePolicy)
        self.TOVC.setObjectName("TOVC")
        self.horizontalLayout_3.addWidget(self.TOVC)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(VTSCHR)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.DELTAY = QtWidgets.QLineEdit(VTSCHR)
        self.DELTAY.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DELTAY.sizePolicy().hasHeightForWidth())
        self.DELTAY.setSizePolicy(sizePolicy)
        self.DELTAY.setObjectName("DELTAY")
        self.horizontalLayout_4.addWidget(self.DELTAY)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(VTSCHR)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.XOVC = QtWidgets.QLineEdit(VTSCHR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XOVC.sizePolicy().hasHeightForWidth())
        self.XOVC.setSizePolicy(sizePolicy)
        self.XOVC.setObjectName("XOVC")
        self.horizontalLayout_5.addWidget(self.XOVC)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(VTSCHR)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.CLI = QtWidgets.QLineEdit(VTSCHR)
        self.CLI.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CLI.sizePolicy().hasHeightForWidth())
        self.CLI.setSizePolicy(sizePolicy)
        self.CLI.setObjectName("CLI")
        self.horizontalLayout_6.addWidget(self.CLI)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(VTSCHR)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.ALPHAI = QtWidgets.QLineEdit(VTSCHR)
        self.ALPHAI.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ALPHAI.sizePolicy().hasHeightForWidth())
        self.ALPHAI.setSizePolicy(sizePolicy)
        self.ALPHAI.setObjectName("ALPHAI")
        self.horizontalLayout_7.addWidget(self.ALPHAI)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(VTSCHR)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.CMO = QtWidgets.QLineEdit(VTSCHR)
        self.CMO.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CMO.sizePolicy().hasHeightForWidth())
        self.CMO.setSizePolicy(sizePolicy)
        self.CMO.setObjectName("CMO")
        self.horizontalLayout_9.addWidget(self.CMO)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(VTSCHR)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.LERI = QtWidgets.QLineEdit(VTSCHR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LERI.sizePolicy().hasHeightForWidth())
        self.LERI.setSizePolicy(sizePolicy)
        self.LERI.setObjectName("LERI")
        self.horizontalLayout_8.addWidget(self.LERI)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(VTSCHR)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.LERO = QtWidgets.QLineEdit(VTSCHR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LERO.sizePolicy().hasHeightForWidth())
        self.LERO.setSizePolicy(sizePolicy)
        self.LERO.setObjectName("LERO")
        self.horizontalLayout_11.addWidget(self.LERO)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(VTSCHR)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.comboBox_CAMBER = QtWidgets.QComboBox(VTSCHR)
        self.comboBox_CAMBER.setObjectName("comboBox_CAMBER")
        self.comboBox_CAMBER.addItem("")
        self.comboBox_CAMBER.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_CAMBER)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_11 = QtWidgets.QLabel(VTSCHR)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.TOVCO = QtWidgets.QLineEdit(VTSCHR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TOVCO.sizePolicy().hasHeightForWidth())
        self.TOVCO.setSizePolicy(sizePolicy)
        self.TOVCO.setObjectName("TOVCO")
        self.horizontalLayout_13.addWidget(self.TOVCO)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(VTSCHR)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        spacerItem10 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.XOVCO = QtWidgets.QLineEdit(VTSCHR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XOVCO.sizePolicy().hasHeightForWidth())
        self.XOVCO.setSizePolicy(sizePolicy)
        self.XOVCO.setObjectName("XOVCO")
        self.horizontalLayout_12.addWidget(self.XOVCO)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(VTSCHR)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        spacerItem11 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.CMOT = QtWidgets.QLineEdit(VTSCHR)
        self.CMOT.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CMOT.sizePolicy().hasHeightForWidth())
        self.CMOT.setSizePolicy(sizePolicy)
        self.CMOT.setObjectName("CMOT")
        self.horizontalLayout_14.addWidget(self.CMOT)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_13 = QtWidgets.QLabel(VTSCHR)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem12)
        self.CLMAXL = QtWidgets.QLineEdit(VTSCHR)
        self.CLMAXL.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CLMAXL.sizePolicy().hasHeightForWidth())
        self.CLMAXL.setSizePolicy(sizePolicy)
        self.CLMAXL.setObjectName("CLMAXL")
        self.horizontalLayout_15.addWidget(self.CLMAXL)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_14 = QtWidgets.QLabel(VTSCHR)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        spacerItem13 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem13)
        self.CLAMO = QtWidgets.QLineEdit(VTSCHR)
        self.CLAMO.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CLAMO.sizePolicy().hasHeightForWidth())
        self.CLAMO.setSizePolicy(sizePolicy)
        self.CLAMO.setObjectName("CLAMO")
        self.horizontalLayout_16.addWidget(self.CLAMO)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_19 = QtWidgets.QLabel(VTSCHR)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_21.addWidget(self.label_19)
        spacerItem14 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem14)
        self.comboBox_DWASH = QtWidgets.QComboBox(VTSCHR)
        self.comboBox_DWASH.setEnabled(False)
        self.comboBox_DWASH.setObjectName("comboBox_DWASH")
        self.comboBox_DWASH.addItem("")
        self.comboBox_DWASH.addItem("")
        self.comboBox_DWASH.addItem("")
        self.horizontalLayout_21.addWidget(self.comboBox_DWASH)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_15 = QtWidgets.QLabel(VTSCHR)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_17.addWidget(self.label_15)
        spacerItem15 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem15)
        self.TCEFF = QtWidgets.QLineEdit(VTSCHR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TCEFF.sizePolicy().hasHeightForWidth())
        self.TCEFF.setSizePolicy(sizePolicy)
        self.TCEFF.setObjectName("TCEFF")
        self.horizontalLayout_17.addWidget(self.TCEFF)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_16 = QtWidgets.QLabel(VTSCHR)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_18.addWidget(self.label_16)
        spacerItem16 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem16)
        self.KSHARP = QtWidgets.QLineEdit(VTSCHR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KSHARP.sizePolicy().hasHeightForWidth())
        self.KSHARP.setSizePolicy(sizePolicy)
        self.KSHARP.setObjectName("KSHARP")
        self.horizontalLayout_18.addWidget(self.KSHARP)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_17 = QtWidgets.QLabel(VTSCHR)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_19.addWidget(self.label_17)
        spacerItem17 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem17)
        self.ARCL = QtWidgets.QLineEdit(VTSCHR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ARCL.sizePolicy().hasHeightForWidth())
        self.ARCL.setSizePolicy(sizePolicy)
        self.ARCL.setObjectName("ARCL")
        self.horizontalLayout_19.addWidget(self.ARCL)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_20 = QtWidgets.QLabel(VTSCHR)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_22.addWidget(self.label_20)
        spacerItem18 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem18)
        self.YCM = QtWidgets.QLineEdit(VTSCHR)
        self.YCM.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YCM.sizePolicy().hasHeightForWidth())
        self.YCM.setSizePolicy(sizePolicy)
        self.YCM.setObjectName("YCM")
        self.horizontalLayout_22.addWidget(self.YCM)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_21 = QtWidgets.QLabel(VTSCHR)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_23.addWidget(self.label_21)
        spacerItem19 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem19)
        self.CLD = QtWidgets.QLineEdit(VTSCHR)
        self.CLD.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CLD.sizePolicy().hasHeightForWidth())
        self.CLD.setSizePolicy(sizePolicy)
        self.CLD.setObjectName("CLD")
        self.horizontalLayout_23.addWidget(self.CLD)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_20.addLayout(self.verticalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(VTSCHR)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_SLOPE = QtWidgets.QCheckBox(self.tab)
        self.checkBox_SLOPE.setEnabled(False)
        self.checkBox_SLOPE.setObjectName("checkBox_SLOPE")
        self.verticalLayout.addWidget(self.checkBox_SLOPE)
        self.tableWidget_SLOPE = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_SLOPE.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_SLOPE.sizePolicy().hasHeightForWidth())
        self.tableWidget_SLOPE.setSizePolicy(sizePolicy)
        self.tableWidget_SLOPE.setObjectName("tableWidget_SLOPE")
        self.tableWidget_SLOPE.setColumnCount(1)
        self.tableWidget_SLOPE.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SLOPE.setHorizontalHeaderItem(0, item)
        self.verticalLayout.addWidget(self.tableWidget_SLOPE)
        self.horizontalLayout_26.addLayout(self.verticalLayout)
        self.tableWidget_Lift = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_Lift.setObjectName("tableWidget_Lift")
        self.tableWidget_Lift.setColumnCount(3)
        self.tableWidget_Lift.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Lift.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Lift.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Lift.setHorizontalHeaderItem(2, item)
        self.tableWidget_Lift.horizontalHeader().setDefaultSectionSize(50)
        self.horizontalLayout_26.addWidget(self.tableWidget_Lift)
        self.tabWidget.addTab(self.tab, "")
        self.tab_Airfoil = QtWidgets.QWidget()
        self.tab_Airfoil.setObjectName("tab_Airfoil")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_Airfoil)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_22 = QtWidgets.QLabel(self.tab_Airfoil)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_24.addWidget(self.label_22)
        spacerItem20 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem20)
        self.comboBox_TYPEIN = QtWidgets.QComboBox(self.tab_Airfoil)
        self.comboBox_TYPEIN.setObjectName("comboBox_TYPEIN")
        self.comboBox_TYPEIN.addItem("")
        self.comboBox_TYPEIN.addItem("")
        self.horizontalLayout_24.addWidget(self.comboBox_TYPEIN)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_24)
        spacerItem21 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem21)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_23 = QtWidgets.QLabel(self.tab_Airfoil)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_25.addWidget(self.label_23)
        spacerItem22 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem22)
        self.NPTS = QtWidgets.QLineEdit(self.tab_Airfoil)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NPTS.sizePolicy().hasHeightForWidth())
        self.NPTS.setSizePolicy(sizePolicy)
        self.NPTS.setObjectName("NPTS")
        self.horizontalLayout_25.addWidget(self.NPTS)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_25)
        self.verticalLayout_3.addLayout(self.horizontalLayout_27)
        self.tableWidget_AirfoilSection = QtWidgets.QTableWidget(self.tab_Airfoil)
        self.tableWidget_AirfoilSection.setObjectName("tableWidget_AirfoilSection")
        self.tableWidget_AirfoilSection.setColumnCount(0)
        self.tableWidget_AirfoilSection.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_AirfoilSection)
        self.tabWidget.addTab(self.tab_Airfoil, "")
        self.tab_para = QtWidgets.QWidget()
        self.tab_para.setObjectName("tab_para")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_para)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser_Help = QtWidgets.QTextBrowser(self.tab_para)
        self.textBrowser_Help.setObjectName("textBrowser_Help")
        self.horizontalLayout.addWidget(self.textBrowser_Help)
        self.tabWidget.addTab(self.tab_para, "")
        self.tab_tips = QtWidgets.QWidget()
        self.tab_tips.setObjectName("tab_tips")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_tips)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_tips)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1310, 895))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_Pic = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Pic.setText("")
        self.label_Pic.setPixmap(QtGui.QPixmap(":/card/rc_card/ARCL.png"))
        self.label_Pic.setObjectName("label_Pic")
        self.horizontalLayout_29.addWidget(self.label_Pic)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_tips, "")
        self.horizontalLayout_20.addWidget(self.tabWidget)
        self.actionDeleteRow = QtWidgets.QAction(VTSCHR)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cardIco/rc_card/icos/DeletedIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteRow.setIcon(icon)
        self.actionDeleteRow.setObjectName("actionDeleteRow")
        self.actionAddRow = QtWidgets.QAction(VTSCHR)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/cardIco/rc_card/icos/AddedIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddRow.setIcon(icon1)
        self.actionAddRow.setObjectName("actionAddRow")

        self.retranslateUi(VTSCHR)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VTSCHR)

    def retranslateUi(self, VTSCHR):
        _translate = QtCore.QCoreApplication.translate
        VTSCHR.setWindowTitle(_translate("VTSCHR", "垂尾气动参数"))
        self.label.setText(_translate("VTSCHR", "TOVC 最大机翼截面厚度"))
        self.label_2.setText(_translate("VTSCHR", "DELTAY 6.0到.15%弦长处翼型差"))
        self.label_3.setText(_translate("VTSCHR", "XOVC  最大机翼厚度的纵坐标"))
        self.label_4.setText(_translate("VTSCHR", "CLI  翼型设计升力系数"))
        self.label_5.setText(_translate("VTSCHR", "ALPHAI 设计攻角 "))
        self.label_7.setToolTip(_translate("VTSCHR", "section zero lift pitching moment coefficient"))
        self.label_7.setText(_translate("VTSCHR", "CMO  截面零升俯仰力矩系数"))
        self.label_6.setToolTip(_translate("VTSCHR", " airfoil leading edge radius fraction of chard     翼型前缘半径 ，参考弦长"))
        self.label_6.setText(_translate("VTSCHR", "LERI 翼型前缘半径"))
        self.label_9.setToolTip(_translate("VTSCHR", "RLE for outboard panel  fraction of chard "))
        self.label_9.setText(_translate("VTSCHR", "LERO  舷外板RLE "))
        self.label_8.setText(_translate("VTSCHR", "CAMBER 弧形翼型截面标志 "))
        self.comboBox_CAMBER.setItemText(0, _translate("VTSCHR", "TRUE"))
        self.comboBox_CAMBER.setItemText(1, _translate("VTSCHR", "FALSE"))
        self.label_11.setToolTip(_translate("VTSCHR", "TOVCO                         t/c for outboard panel"))
        self.label_11.setText(_translate("VTSCHR", "TOVCO "))
        self.label_10.setToolTip(_translate("VTSCHR", "(x/c)max for outboard panel"))
        self.label_10.setText(_translate("VTSCHR", "XOVCO"))
        self.label_12.setToolTip(_translate("VTSCHR", "Cmo for outboard panel"))
        self.label_12.setText(_translate("VTSCHR", "CMOT"))
        self.label_13.setToolTip(_translate("VTSCHR", " airfoil maximum lift coefficient at MACH equal Zero"))
        self.label_13.setText(_translate("VTSCHR", "CLMAXL"))
        self.label_14.setToolTip(_translate("VTSCHR", "airfoil section lift curve slope at MACH equal Zero\n"
""))
        self.label_14.setText(_translate("VTSCHR", "CLAMO"))
        self.label_19.setToolTip(_translate("VTSCHR", "DWASH                         subsonic downwash method flag \n"
"                              =1. use datcom method 1                   \n"
"                              =2. use datcom method 2  \n"
"                              =3. use datcom method 3  \n"
"                              Supersonic ,use datcom method 2 if dwash =1 or 2 (see figure 9)"))
        self.label_19.setText(_translate("VTSCHR", "DWASH 下洗算法"))
        self.comboBox_DWASH.setToolTip(_translate("VTSCHR", "与速度域有关"))
        self.comboBox_DWASH.setItemText(0, _translate("VTSCHR", "1.0"))
        self.comboBox_DWASH.setItemText(1, _translate("VTSCHR", "2.0"))
        self.comboBox_DWASH.setItemText(2, _translate("VTSCHR", "3.0"))
        self.label_15.setToolTip(_translate("VTSCHR", " planform effective thickness ratio，fraction of chord"))
        self.label_15.setText(_translate("VTSCHR", "TCEFF"))
        self.label_16.setToolTip(_translate("VTSCHR", " wave drag factor for sharp-nosed airfoil section，not input for round nosed airfoil"))
        self.label_16.setText(_translate("VTSCHR", "KSHARP 波阻系数"))
        self.label_17.setToolTip(_translate("VTSCHR", "aspect ratio classification"))
        self.label_17.setText(_translate("VTSCHR", "ARCL"))
        self.label_20.setToolTip(_translate("VTSCHR", "airfoil maximum camber， fraction of chord"))
        self.label_20.setText(_translate("VTSCHR", "YCM"))
        self.label_21.setToolTip(_translate("VTSCHR", "conical camber design lift coefficient for M=1.0 Design. See-NACA RM A55G19.(Default To 0.0)"))
        self.label_21.setText(_translate("VTSCHR", "CLD"))
        self.CLD.setText(_translate("VTSCHR", "0.0"))
        self.checkBox_SLOPE.setToolTip(_translate("VTSCHR", "airfoil surface slope at 0 ，20,40,60,80,100% chord ，DEG.Positive when the\n"
" tangent intersects the chord plane forward of the reference chord point"))
        self.checkBox_SLOPE.setText(_translate("VTSCHR", "SLOPE"))
        item = self.tableWidget_SLOPE.horizontalHeaderItem(0)
        item.setText(_translate("VTSCHR", "SLOPE"))
        self.tableWidget_Lift.setToolTip(_translate("VTSCHR", "输入值必须和飞行条件中的VIF匹配"))
        item = self.tableWidget_Lift.horizontalHeaderItem(0)
        item.setText(_translate("VTSCHR", "CLALPA"))
        item = self.tableWidget_Lift.horizontalHeaderItem(1)
        item.setText(_translate("VTSCHR", "CLMAX"))
        item = self.tableWidget_Lift.horizontalHeaderItem(2)
        item.setText(_translate("VTSCHR", "XAC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("VTSCHR", "SLOPE CLALPA XAC"))
        self.label_22.setToolTip(_translate("VTSCHR", "TYPEIN    翼型截面坐标模式    type of airfoil section coordinate input for airfoil section module\n"
"                              = 1.0 upper and lower surface coordinates(Y Upper and Y Lower)\n"
"                              = 2.0 mean line and thickness distribution (mean and thick)"))
        self.label_22.setText(_translate("VTSCHR", "TYPEIN 翼型截面坐标模式"))
        self.comboBox_TYPEIN.setToolTip(_translate("VTSCHR", "\n"
"TYPEIN    翼型截面坐标模式    type of airfoil section coordinate input for airfoil section module\n"
"                              = 1.0 upper and lower surface coordinates(Y Upper and Y Lower)\n"
"                              = 2.0 mean line and thickness distribution (mean and thick)"))
        self.comboBox_TYPEIN.setItemText(0, _translate("VTSCHR", "1.0 上下表面"))
        self.comboBox_TYPEIN.setItemText(1, _translate("VTSCHR", "2.0 中线厚度"))
        self.label_23.setToolTip(_translate("VTSCHR", "number of section point input,Max =50"))
        self.label_23.setText(_translate("VTSCHR", "NPTS  截面点数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Airfoil), _translate("VTSCHR", "翼型定义"))
        self.textBrowser_Help.setHtml(_translate("VTSCHR", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TOVC   最大机翼厚度  maximum airfoil section thickness ,fraction of chord   最大机翼厚度是弦长的分数</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DELTAY 6.0到.15%弦长处翼型差    difference between airfoil ordinates at 6.0 AND .15% chord ,percent chord  6.0到.15%弦长处翼型的差</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">XOVC  机翼最厚处纵坐标  chord location of maximum airfoil thickness, fraction of chord    最大机翼厚度的纵坐标</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CLI   翼型设计升力系数  airfoil section design lift coefficient  翼型设计升力系数</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ALPHAI 设计攻角 angle of attack at section design lift coefficient,edg 翼型设计升力系数对应的攻角</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CLALPA  翼型升力曲线   20  airfoil section lift curve slope dCl/dα ,per DEG 翼型升力曲线 斜率 dCl/dα 每度</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CLMAX   翼型最大升力系数  20  airfoil section maximum lift coefficient          翼型最大升力系数</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CMO CM0  零段升力俯仰力矩系数       section zero lift pitching moment coefficient 零段升力俯仰力矩系数</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LERI    翼型前缘半径分数      airfoil leading edge radius fraction of chard</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LERO     舷外板RLE            RLE for outboard panel  fraction of chard      舷外板RLE 参考弦长</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CAMBER   弧形翼型截面标志  =TRUE                   cambered airfoil section flag</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TOVCO                         t/c for outboard panel</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">XOVCO                         (x/c)max for outboard panel</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CMOT CM0T                     Cmo for outboard panel</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CLMAXL                        airfoil maximum lift coefficient at MACH equal Zero</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TCEFF                         planform effective thickness ratio，fraction of chord</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">KSHARP    波阻系数            wave drag factor for sharp-nosed airfoil section，not input for round nosed airfoil</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SLOPE                         airfoil surface slope at 0 ，20,40,60,80,100% chord ，DEG.Positive when the</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> tangent intersects the chord plane forward of the reference chord point</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ARCL                          aspect ratio classification </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">XAC                       20  section aerodynamic center，fraction of chord (see vol II for default)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DWASH                         subsonic downwash method flag </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                              =1. use datcom method 1                   </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                              =2. use datcom method 2  </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                              =3. use datcom method 3  </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                              Supersonic ,use datcom method 2 if dwash =1 or 2 (see figure 9)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">YCM                           airfoil maximum camber， fraction of chord</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CLD                       0.0 conical camber design lift coefficient for M=1.0 Design. See-NACA RM A55G19.(Default To 0.0)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TYPEIN    翼型截面坐标模式    type of airfoil section coordinate input for airfoil section module</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                              = 1.0 upper and lower surface coordinates(Y Upper and Y Lower)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                              = 2.0 mean line and thickness distribution (mean and thick)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">NPTS      截面点数         50 number of section point input,Max =50</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">XCORD     输入点横坐标     50 abscissas of input points，</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                              TYPEIN =1.0 or 2.0 ,XCORD（1）=0.0，XCORD（NPTS）=1.0</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">YUPPER                     50 ordinates of upper surface.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                              TYPEIN =1.0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                              FRACTION OF CHORD ,and requires YUPPER(1)=0.0 YUPPER(NPTS)=0.0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">YLOWER                     50 ordinates of lower surface.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                              TYPEIN =1.0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                              FRACTION OF CHORD ,and requires YLOWER(1)=0.0 YLOWER(NPTS)=0.0</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MEAN                       50 ordinates of mean line .TYPEIN =2.0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                              FRACTION OF CHORD ,and requires MEAN(1)=0.0 MEAN(NPTS)=0.0</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">THICK                      50 thikness distribution .TYPEIN =2.0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                              FRACTION OF CHORD ,and requires THICK(1)=0.0 THICK(NPTS)=0.0</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_para), _translate("VTSCHR", "参数说明"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tips), _translate("VTSCHR", "提示信息"))
        self.actionDeleteRow.setText(_translate("VTSCHR", "删除行"))
        self.actionDeleteRow.setToolTip(_translate("VTSCHR", "删除一行"))
        self.actionAddRow.setText(_translate("VTSCHR", "增加行"))
        self.actionAddRow.setToolTip(_translate("VTSCHR", "新增行"))

import card_ico_rc
import card_rc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VTSCHR = QtWidgets.QWidget()
    ui = Ui_VTSCHR()
    ui.setupUi(VTSCHR)
    VTSCHR.show()
    sys.exit(app.exec_())

