# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\PlaneConfiguration\VTPLNF.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(845, 577)
        self.lineEdit_SSPN = QtWidgets.QLineEdit(Form)
        self.lineEdit_SSPN.setGeometry(QtCore.QRect(260, 291, 133, 20))
        self.lineEdit_SSPN.setObjectName("lineEdit_SSPN")
        self.lineEdit_SSPNOP = QtWidgets.QLineEdit(Form)
        self.lineEdit_SSPNOP.setGeometry(QtCore.QRect(260, 211, 133, 20))
        self.lineEdit_SSPNOP.setObjectName("lineEdit_SSPNOP")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 243, 180, 35))
        self.label_4.setObjectName("label_4")
        self.label_SAVSO = QtWidgets.QLabel(Form)
        self.label_SAVSO.setGeometry(QtCore.QRect(50, 449, 180, 35))
        self.label_SAVSO.setObjectName("label_SAVSO")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 284, 180, 36))
        self.label_5.setObjectName("label_5")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(680, 358, 500, 300))
        self.label_16.setObjectName("label_16")
        self.lineEdit_CHSTAT = QtWidgets.QLineEdit(Form)
        self.lineEdit_CHSTAT.setGeometry(QtCore.QRect(260, 501, 133, 20))
        self.lineEdit_CHSTAT.setObjectName("lineEdit_CHSTAT")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 202, 180, 35))
        self.label_3.setObjectName("label_3")
        self.lineEdit_MACHN = QtWidgets.QLineEdit(Form)
        self.lineEdit_MACHN.setGeometry(QtCore.QRect(260, 128, 133, 20))
        self.lineEdit_MACHN.setObjectName("lineEdit_MACHN")
        self.lineEdit_CHRDR = QtWidgets.QLineEdit(Form)
        self.lineEdit_CHRDR.setGeometry(QtCore.QRect(260, 371, 133, 20))
        self.lineEdit_CHRDR.setObjectName("lineEdit_CHRDR")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(50, 118, 180, 35))
        self.label_15.setObjectName("label_15")
        self.lineEdit_CHRDTP = QtWidgets.QLineEdit(Form)
        self.lineEdit_CHRDTP.setGeometry(QtCore.QRect(260, 171, 133, 20))
        self.lineEdit_CHRDTP.setObjectName("lineEdit_CHRDTP")
        self.image_VTPLNF = QtWidgets.QLabel(Form)
        self.image_VTPLNF.setGeometry(QtCore.QRect(680, 68, 500, 300))
        self.image_VTPLNF.setObjectName("image_VTPLNF")
        self.lineEdit_CHRDBP = QtWidgets.QLineEdit(Form)
        self.lineEdit_CHRDBP.setGeometry(QtCore.QRect(260, 331, 133, 20))
        self.lineEdit_CHRDBP.setObjectName("lineEdit_CHRDBP")
        self.lineEdit_SSPNE = QtWidgets.QLineEdit(Form)
        self.lineEdit_SSPNE.setGeometry(QtCore.QRect(260, 251, 133, 20))
        self.lineEdit_SSPNE.setObjectName("lineEdit_SSPNE")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 161, 180, 35))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(50, 326, 180, 35))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 51, 61, 32))
        self.label.setObjectName("label")
        self.lineEdit_SAVSO = QtWidgets.QLineEdit(Form)
        self.lineEdit_SAVSO.setGeometry(QtCore.QRect(260, 461, 133, 20))
        self.lineEdit_SAVSO.setObjectName("lineEdit_SAVSO")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(410, 58, 251, 531))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.comboBox_WShape = QtWidgets.QComboBox(Form)
        self.comboBox_WShape.setGeometry(QtCore.QRect(150, 61, 181, 22))
        self.comboBox_WShape.setObjectName("comboBox_WShape")
        self.comboBox_WShape.addItem("")
        self.comboBox_WShape.addItem("")
        self.comboBox_WShape.addItem("")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(50, 367, 180, 35))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(50, 408, 180, 35))
        self.label_8.setObjectName("label_8")
        self.lineEdit_SAVSI = QtWidgets.QLineEdit(Form)
        self.lineEdit_SAVSI.setGeometry(QtCore.QRect(260, 421, 133, 20))
        self.lineEdit_SAVSI.setObjectName("lineEdit_SAVSI")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(50, 490, 180, 35))
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "SSPNE：外露板半展长"))
        self.label_SAVSO.setText(_translate("Form", "SAVSO：外侧板掠角"))
        self.label_5.setText(_translate("Form", "SSPN：理论根弦的理论半展长"))
        self.label_16.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "SSPNOP：外侧板半展长"))
        self.label_15.setText(_translate("Form", "马赫数（与飞行页一致）"))
        self.image_VTPLNF.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "CHRDTP：稍弦长"))
        self.label_6.setText(_translate("Form", "CHRDBP：断点弦长"))
        self.label.setText(_translate("Form", "机翼类型"))
        self.comboBox_WShape.setItemText(0, _translate("Form", "1.0 直锥型外形"))
        self.comboBox_WShape.setItemText(1, _translate("Form", "2.0 双三角翼型外形（展现比≤3）"))
        self.comboBox_WShape.setItemText(2, _translate("Form", "3.0 边条型外形（展弦比≤3）"))
        self.label_7.setText(_translate("Form", "CHRDR：根弦长"))
        self.label_8.setText(_translate("Form", "SAVSI：内侧板掠角"))
        self.label_10.setText(_translate("Form", "CHSTAT：内外侧板掠角的参考弦点"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

