# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\PlaneConfiguration\WGPLNF.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(970, 421)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.comboBox_TYPE = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_TYPE.sizePolicy().hasHeightForWidth())
        self.comboBox_TYPE.setSizePolicy(sizePolicy)
        self.comboBox_TYPE.setObjectName("comboBox_TYPE")
        self.comboBox_TYPE.addItem("")
        self.comboBox_TYPE.addItem("")
        self.comboBox_TYPE.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_TYPE)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lineEdit_CHRDTP = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CHRDTP.sizePolicy().hasHeightForWidth())
        self.lineEdit_CHRDTP.setSizePolicy(sizePolicy)
        self.lineEdit_CHRDTP.setObjectName("lineEdit_CHRDTP")
        self.horizontalLayout.addWidget(self.lineEdit_CHRDTP)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.lineEdit_CHRDBP = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CHRDBP.sizePolicy().hasHeightForWidth())
        self.lineEdit_CHRDBP.setSizePolicy(sizePolicy)
        self.lineEdit_CHRDBP.setObjectName("lineEdit_CHRDBP")
        self.horizontalLayout_5.addWidget(self.lineEdit_CHRDBP)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.lineEdit_CHRDR = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CHRDR.sizePolicy().hasHeightForWidth())
        self.lineEdit_CHRDR.setSizePolicy(sizePolicy)
        self.lineEdit_CHRDR.setObjectName("lineEdit_CHRDR")
        self.horizontalLayout_6.addWidget(self.lineEdit_CHRDR)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.lineEdit_SSPNOP = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SSPNOP.sizePolicy().hasHeightForWidth())
        self.lineEdit_SSPNOP.setSizePolicy(sizePolicy)
        self.lineEdit_SSPNOP.setObjectName("lineEdit_SSPNOP")
        self.horizontalLayout_2.addWidget(self.lineEdit_SSPNOP)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.lineEdit_SSPNE = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SSPNE.sizePolicy().hasHeightForWidth())
        self.lineEdit_SSPNE.setSizePolicy(sizePolicy)
        self.lineEdit_SSPNE.setObjectName("lineEdit_SSPNE")
        self.horizontalLayout_3.addWidget(self.lineEdit_SSPNE)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem6 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.lineEdit_SSPN = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SSPN.sizePolicy().hasHeightForWidth())
        self.lineEdit_SSPN.setSizePolicy(sizePolicy)
        self.lineEdit_SSPN.setObjectName("lineEdit_SSPN")
        self.horizontalLayout_4.addWidget(self.lineEdit_SSPN)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        spacerItem7 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.lineEdit_SAVSI = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SAVSI.sizePolicy().hasHeightForWidth())
        self.lineEdit_SAVSI.setSizePolicy(sizePolicy)
        self.lineEdit_SAVSI.setObjectName("lineEdit_SAVSI")
        self.horizontalLayout_7.addWidget(self.lineEdit_SAVSI)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_SAVSO = QtWidgets.QLabel(Form)
        self.label_SAVSO.setObjectName("label_SAVSO")
        self.horizontalLayout_8.addWidget(self.label_SAVSO)
        spacerItem8 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.lineEdit_SAVSO = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SAVSO.sizePolicy().hasHeightForWidth())
        self.lineEdit_SAVSO.setSizePolicy(sizePolicy)
        self.lineEdit_SAVSO.setObjectName("lineEdit_SAVSO")
        self.horizontalLayout_8.addWidget(self.lineEdit_SAVSO)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        spacerItem9 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.lineEdit_TWISTA = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_TWISTA.sizePolicy().hasHeightForWidth())
        self.lineEdit_TWISTA.setSizePolicy(sizePolicy)
        self.lineEdit_TWISTA.setObjectName("lineEdit_TWISTA")
        self.horizontalLayout_10.addWidget(self.lineEdit_TWISTA)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        spacerItem10 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.lineEdit_CHSTAT = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CHSTAT.sizePolicy().hasHeightForWidth())
        self.lineEdit_CHSTAT.setSizePolicy(sizePolicy)
        self.lineEdit_CHSTAT.setObjectName("lineEdit_CHSTAT")
        self.horizontalLayout_9.addWidget(self.lineEdit_CHSTAT)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        spacerItem11 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.lineEdit_SSPNDD = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SSPNDD.sizePolicy().hasHeightForWidth())
        self.lineEdit_SSPNDD.setSizePolicy(sizePolicy)
        self.lineEdit_SSPNDD.setObjectName("lineEdit_SSPNDD")
        self.horizontalLayout_11.addWidget(self.lineEdit_SSPNDD)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        spacerItem12 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem12)
        self.lineEdit_DHDADI = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_DHDADI.sizePolicy().hasHeightForWidth())
        self.lineEdit_DHDADI.setSizePolicy(sizePolicy)
        self.lineEdit_DHDADI.setObjectName("lineEdit_DHDADI")
        self.horizontalLayout_12.addWidget(self.lineEdit_DHDADI)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        spacerItem13 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.lineEdit_DHDADO = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_DHDADO.sizePolicy().hasHeightForWidth())
        self.lineEdit_DHDADO.setSizePolicy(sizePolicy)
        self.lineEdit_DHDADO.setObjectName("lineEdit_DHDADO")
        self.horizontalLayout_13.addWidget(self.lineEdit_DHDADO)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15.addLayout(self.verticalLayout)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_16.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/card/rc_card/WGPLNF.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_17.addWidget(self.label_9)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/card/rc_card/WGPLNF_Para.png"))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_18.addWidget(self.label_15)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_15.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "机翼外形定义"))
        self.label.setText(_translate("Form", "机翼类型"))
        self.comboBox_TYPE.setItemText(0, _translate("Form", "1.0 直锥型外形"))
        self.comboBox_TYPE.setItemText(1, _translate("Form", "2.0 双三角翼型外形（展弦比≤3）"))
        self.comboBox_TYPE.setItemText(2, _translate("Form", "3.0 边条型外形（展弦比≤3）"))
        self.label_2.setText(_translate("Form", "CHRDTP：稍弦长"))
        self.label_6.setText(_translate("Form", "CHRDBP：断点弦长"))
        self.label_7.setText(_translate("Form", "CHRDR：根弦长"))
        self.label_3.setText(_translate("Form", "SSPNOP：外侧板半展长"))
        self.label_4.setText(_translate("Form", "SSPNE：外露板半展长"))
        self.label_5.setText(_translate("Form", "SSPN：理论根弦的理论半展长"))
        self.label_8.setText(_translate("Form", "SAVSI：内侧板掠角"))
        self.label_SAVSO.setText(_translate("Form", "SAVSO：外侧板掠角"))
        self.label_11.setText(_translate("Form", "TWISTA：扭转角"))
        self.label_10.setText(_translate("Form", "CHSTAT：内外侧板掠角的参考弦点"))
        self.label_12.setText(_translate("Form", "SSPNDD：内上反角的外侧板半展长"))
        self.label_13.setText(_translate("Form", "DHDADI：内侧板上反角"))
        self.label_14.setText(_translate("Form", "DHDADO：外侧板上反角"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "说明"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "示意图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "页"))

import card_rc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

