# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\tools\XMLEditer.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_XMLEditer(object):
    def setupUi(self, XMLEditer):
        XMLEditer.setObjectName("XMLEditer")
        XMLEditer.resize(926, 585)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tools/res/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        XMLEditer.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(XMLEditer)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget_xml = QtWidgets.QTreeWidget(self.centralWidget)
        self.treeWidget_xml.setObjectName("treeWidget_xml")
        self.horizontalLayout.addWidget(self.treeWidget_xml)
        XMLEditer.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(XMLEditer)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 926, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuExtraTools = QtWidgets.QMenu(self.menuBar)
        self.menuExtraTools.setObjectName("menuExtraTools")
        XMLEditer.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(XMLEditer)
        self.statusBar.setObjectName("statusBar")
        XMLEditer.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(XMLEditer)
        self.toolBar.setObjectName("toolBar")
        XMLEditer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoadXML = QtWidgets.QAction(XMLEditer)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/tools/res/dirOpen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoadXML.setIcon(icon1)
        self.actionLoadXML.setObjectName("actionLoadXML")
        self.actionSave_XML = QtWidgets.QAction(XMLEditer)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/tools/res/fileSave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_XML.setIcon(icon2)
        self.actionSave_XML.setObjectName("actionSave_XML")
        self.actionSave_as_XML = QtWidgets.QAction(XMLEditer)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/tools/res/fileSaveAs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as_XML.setIcon(icon3)
        self.actionSave_as_XML.setObjectName("actionSave_as_XML")
        self.actionUnload = QtWidgets.QAction(XMLEditer)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/tools/res/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnload.setIcon(icon4)
        self.actionUnload.setObjectName("actionUnload")
        self.actionReload = QtWidgets.QAction(XMLEditer)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/tools/res/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReload.setIcon(icon5)
        self.actionReload.setObjectName("actionReload")
        self.actionReadOnlyMode = QtWidgets.QAction(XMLEditer)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/tools/res/documentFind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReadOnlyMode.setIcon(icon6)
        self.actionReadOnlyMode.setObjectName("actionReadOnlyMode")
        self.actionValueOnlyMode = QtWidgets.QAction(XMLEditer)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/tools/res/deleteShape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionValueOnlyMode.setIcon(icon7)
        self.actionValueOnlyMode.setObjectName("actionValueOnlyMode")
        self.actionAllMode = QtWidgets.QAction(XMLEditer)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/tools/res/compareFiles.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAllMode.setIcon(icon8)
        self.actionAllMode.setObjectName("actionAllMode")
        self.actionReLoadCaseUI = QtWidgets.QAction(XMLEditer)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/nodes/res/qscintilla.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReLoadCaseUI.setIcon(icon9)
        self.actionReLoadCaseUI.setObjectName("actionReLoadCaseUI")
        self.menuFile.addAction(self.actionLoadXML)
        self.menuFile.addAction(self.actionUnload)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_XML)
        self.menuFile.addAction(self.actionSave_as_XML)
        self.menuFile.addAction(self.actionReload)
        self.menuTools.addAction(self.actionReadOnlyMode)
        self.menuTools.addAction(self.actionValueOnlyMode)
        self.menuTools.addAction(self.actionAllMode)
        self.menuExtraTools.addAction(self.actionReLoadCaseUI)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuExtraTools.menuAction())
        self.toolBar.addAction(self.actionLoadXML)
        self.toolBar.addAction(self.actionUnload)
        self.toolBar.addAction(self.actionReload)
        self.toolBar.addAction(self.actionSave_XML)
        self.toolBar.addAction(self.actionSave_as_XML)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionReadOnlyMode)
        self.toolBar.addAction(self.actionValueOnlyMode)
        self.toolBar.addAction(self.actionAllMode)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionReLoadCaseUI)

        self.retranslateUi(XMLEditer)
        QtCore.QMetaObject.connectSlotsByName(XMLEditer)

    def retranslateUi(self, XMLEditer):
        _translate = QtCore.QCoreApplication.translate
        XMLEditer.setWindowTitle(_translate("XMLEditer", "XMl编辑器"))
        self.treeWidget_xml.headerItem().setText(0, _translate("XMLEditer", "节点"))
        self.treeWidget_xml.headerItem().setText(1, _translate("XMLEditer", "值"))
        self.menuFile.setTitle(_translate("XMLEditer", "File"))
        self.menuTools.setTitle(_translate("XMLEditer", "Tools"))
        self.menuExtraTools.setTitle(_translate("XMLEditer", "外部命令"))
        self.toolBar.setWindowTitle(_translate("XMLEditer", "工具栏"))
        self.actionLoadXML.setText(_translate("XMLEditer", "加载XML"))
        self.actionLoadXML.setShortcut(_translate("XMLEditer", "Ctrl+O"))
        self.actionSave_XML.setText(_translate("XMLEditer", "保存"))
        self.actionSave_XML.setShortcut(_translate("XMLEditer", "Ctrl+S"))
        self.actionSave_as_XML.setText(_translate("XMLEditer", "另存为"))
        self.actionSave_as_XML.setShortcut(_translate("XMLEditer", "Ctrl+Shift+S"))
        self.actionUnload.setText(_translate("XMLEditer", "关闭"))
        self.actionReload.setText(_translate("XMLEditer", "重新加载"))
        self.actionReadOnlyMode.setText(_translate("XMLEditer", "只读模式"))
        self.actionValueOnlyMode.setText(_translate("XMLEditer", "值可编辑模式"))
        self.actionAllMode.setText(_translate("XMLEditer", "完全可编辑模式"))
        self.actionReLoadCaseUI.setText(_translate("XMLEditer", "重载CASE的UI"))

import tools_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    XMLEditer = QtWidgets.QMainWindow()
    ui = Ui_XMLEditer()
    ui.setupUi(XMLEditer)
    XMLEditer.show()
    sys.exit(app.exec_())

