# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\tests\parserBuild\datcomParsermain.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_reDatcomparser(object):
    def setupUi(self, reDatcomparser):
        reDatcomparser.setObjectName("reDatcomparser")
        reDatcomparser.resize(1039, 602)
        self.centralWidget = QtWidgets.QWidget(reDatcomparser)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_Modul = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Modul.sizePolicy().hasHeightForWidth())
        self.lineEdit_Modul.setSizePolicy(sizePolicy)
        self.lineEdit_Modul.setObjectName("lineEdit_Modul")
        self.horizontalLayout.addWidget(self.lineEdit_Modul)
        self.pushButton_load = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout.addWidget(self.pushButton_load)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.comboBox_re = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_re.sizePolicy().hasHeightForWidth())
        self.comboBox_re.setSizePolicy(sizePolicy)
        self.comboBox_re.setObjectName("comboBox_re")
        self.horizontalLayout_2.addWidget(self.comboBox_re)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.plainTextEdit_reg = QtWidgets.QPlainTextEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_reg.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_reg.setSizePolicy(sizePolicy)
        self.plainTextEdit_reg.setObjectName("plainTextEdit_reg")
        self.verticalLayout.addWidget(self.plainTextEdit_reg)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_file = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_file.setObjectName("lineEdit_file")
        self.horizontalLayout_3.addWidget(self.lineEdit_file)
        self.pushButton_click = QtWidgets.QPushButton(self.tab)
        self.pushButton_click.setObjectName("pushButton_click")
        self.horizontalLayout_3.addWidget(self.pushButton_click)
        self.pushButton_Run = QtWidgets.QPushButton(self.tab)
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.horizontalLayout_3.addWidget(self.pushButton_Run)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.plainTextEdit_input = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_input.setObjectName("plainTextEdit_input")
        self.verticalLayout_2.addWidget(self.plainTextEdit_input)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.plainTextEdit_match = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_match.setObjectName("plainTextEdit_match")
        self.horizontalLayout_4.addWidget(self.plainTextEdit_match)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        reDatcomparser.setCentralWidget(self.centralWidget)
        self.actionRun = QtWidgets.QAction(reDatcomparser)
        self.actionRun.setObjectName("actionRun")

        self.retranslateUi(reDatcomparser)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(reDatcomparser)

    def retranslateUi(self, reDatcomparser):
        _translate = QtCore.QCoreApplication.translate
        reDatcomparser.setWindowTitle(_translate("reDatcomparser", "正则表达式"))
        self.label.setText(_translate("reDatcomparser", "模块"))
        self.pushButton_load.setText(_translate("reDatcomparser", "加载模块"))
        self.label_2.setText(_translate("reDatcomparser", "表达式"))
        self.label_3.setText(_translate("reDatcomparser", "待诗选文本"))
        self.pushButton_click.setText(_translate("reDatcomparser", "....."))
        self.pushButton_Run.setText(_translate("reDatcomparser", "分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("reDatcomparser", "待筛选"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("reDatcomparser", "结果"))
        self.actionRun.setText(_translate("reDatcomparser", "执行"))
        self.actionRun.setToolTip(_translate("reDatcomparser", "<html><head/><body><p>执行分析</p></body></html>"))
        self.actionRun.setShortcut(_translate("reDatcomparser", "Ctrl+R"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    reDatcomparser = QtWidgets.QMainWindow()
    ui = Ui_reDatcomparser()
    ui.setupUi(reDatcomparser)
    reDatcomparser.show()
    sys.exit(app.exec_())

