# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\components\logForm.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(422, 319)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mainwindow/images/mainwindow/logger.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dockWidget = QtWidgets.QDockWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(174, 38))
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(self.dockWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 0, 352, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton_Clear = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_Clear.sizePolicy().hasHeightForWidth())
        self.toolButton_Clear.setSizePolicy(sizePolicy)
        self.toolButton_Clear.setMinimumSize(QtCore.QSize(25, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/mainwindow/images/mainwindow/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Clear.setIcon(icon1)
        self.toolButton_Clear.setObjectName("toolButton_Clear")
        self.horizontalLayout.addWidget(self.toolButton_Clear)
        self.toolButton_Error = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_Error.sizePolicy().hasHeightForWidth())
        self.toolButton_Error.setSizePolicy(sizePolicy)
        self.toolButton_Error.setMinimumSize(QtCore.QSize(25, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/mainwindow/images/mainwindow/error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Error.setIcon(icon2)
        self.toolButton_Error.setObjectName("toolButton_Error")
        self.horizontalLayout.addWidget(self.toolButton_Error)
        self.toolButton_Debug = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_Debug.sizePolicy().hasHeightForWidth())
        self.toolButton_Debug.setSizePolicy(sizePolicy)
        self.toolButton_Debug.setMinimumSize(QtCore.QSize(25, 25))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/mainwindow/images/mainwindow/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Debug.setIcon(icon3)
        self.toolButton_Debug.setObjectName("toolButton_Debug")
        self.horizontalLayout.addWidget(self.toolButton_Debug)
        self.toolButton_Info = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_Info.sizePolicy().hasHeightForWidth())
        self.toolButton_Info.setSizePolicy(sizePolicy)
        self.toolButton_Info.setMinimumSize(QtCore.QSize(25, 25))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/mainwindow/images/mainwindow/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Info.setIcon(icon4)
        self.toolButton_Info.setObjectName("toolButton_Info")
        self.horizontalLayout.addWidget(self.toolButton_Info)
        spacerItem = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.verticalLayout.addWidget(self.dockWidget)
        self.plainTextEdit_log = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_log.setObjectName("plainTextEdit_log")
        self.verticalLayout.addWidget(self.plainTextEdit_log)
        self.actionClearLog = QtWidgets.QAction(Form)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icos/cBreak.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClearLog.setIcon(icon5)
        self.actionClearLog.setObjectName("actionClearLog")
        self.actionDebugLevel = QtWidgets.QAction(Form)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icos/debug48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDebugLevel.setIcon(icon6)
        self.actionDebugLevel.setObjectName("actionDebugLevel")
        self.actionInfoLevel = QtWidgets.QAction(Form)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icos/preferences-calltips.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInfoLevel.setIcon(icon7)
        self.actionInfoLevel.setObjectName("actionInfoLevel")
        self.actionErrorLevel = QtWidgets.QAction(Form)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icos/exceptions.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionErrorLevel.setIcon(icon8)
        self.actionErrorLevel.setObjectName("actionErrorLevel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "日志窗口"))
        self.toolButton_Clear.setText(_translate("Form", "..."))
        self.toolButton_Error.setText(_translate("Form", "..."))
        self.toolButton_Debug.setText(_translate("Form", "..."))
        self.toolButton_Info.setText(_translate("Form", "..."))
        self.actionClearLog.setText(_translate("Form", "ClearLog"))
        self.actionClearLog.setToolTip(_translate("Form", "清理日志"))
        self.actionDebugLevel.setText(_translate("Form", "DebugLevel"))
        self.actionDebugLevel.setToolTip(_translate("Form", "设置为DebugLevel"))
        self.actionInfoLevel.setText(_translate("Form", "InfoLevel"))
        self.actionInfoLevel.setToolTip(_translate("Form", "设置为Info等级"))
        self.actionErrorLevel.setText(_translate("Form", "ErrorLevel"))
        self.actionErrorLevel.setToolTip(_translate("Form", "设置为错误级别"))

import PyDatcomLab_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

