# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Projects\PyDatcomLab\PyDatcomLab\GUIs\components\ProjectsManager.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProjectsMainWindow(object):
    def setupUi(self, ProjectsMainWindow):
        ProjectsMainWindow.setObjectName("ProjectsMainWindow")
        #ProjectsMainWindow.resize(300, 600)
        self.centralWidget = QtWidgets.QWidget(ProjectsMainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_projectChoise = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_projectChoise.sizePolicy().hasHeightForWidth())
        self.pushButton_projectChoise.setSizePolicy(sizePolicy)
        self.pushButton_projectChoise.setObjectName("pushButton_projectChoise")
        self.horizontalLayout.addWidget(self.pushButton_projectChoise)
        self.comboBox_project = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_project.setObjectName("comboBox_project")
        self.horizontalLayout.addWidget(self.comboBox_project)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.treeView_xml = QtWidgets.QTreeView(self.centralWidget)
        self.treeView_xml.setObjectName("treeView_xml")
        self.verticalLayout.addWidget(self.treeView_xml)
        ProjectsMainWindow.setCentralWidget(self.centralWidget)
        self.toolBar = QtWidgets.QToolBar(ProjectsMainWindow)
        self.toolBar.setObjectName("toolBar")
        ProjectsMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNewCase = QtWidgets.QAction(ProjectsMainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/prjManger/icos/tabNew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewCase.setIcon(icon)
        self.actionNewCase.setObjectName("actionNewCase")
        self.actionCopyCase = QtWidgets.QAction(ProjectsMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/prjManger/icos/tabDuplicate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopyCase.setIcon(icon1)
        self.actionCopyCase.setObjectName("actionCopyCase")
        self.actionAddCase = QtWidgets.QAction(ProjectsMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/prjManger/icos/tabManager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddCase.setIcon(icon2)
        self.actionAddCase.setObjectName("actionAddCase")
        self.actionRemoveCase = QtWidgets.QAction(ProjectsMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/prjManger/icos/tabCloseOther.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemoveCase.setIcon(icon3)
        self.actionRemoveCase.setObjectName("actionRemoveCase")
        self.actionNewGroup = QtWidgets.QAction(ProjectsMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/prjManger/icos/vcsAdd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewGroup.setIcon(icon4)
        self.actionNewGroup.setObjectName("actionNewGroup")
        self.actionAddGroup = QtWidgets.QAction(ProjectsMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/prjManger/icos/vcsCheckout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddGroup.setIcon(icon5)
        self.actionAddGroup.setObjectName("actionAddGroup")
        self.actionCopyGroup = QtWidgets.QAction(ProjectsMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/prjManger/icos/vcsBranch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopyGroup.setIcon(icon6)
        self.actionCopyGroup.setObjectName("actionCopyGroup")
        self.actionRemoveGroup = QtWidgets.QAction(ProjectsMainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/prjManger/icos/vcsAddRemove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemoveGroup.setIcon(icon7)
        self.actionRemoveGroup.setObjectName("actionRemoveGroup")
        self.toolBar.addAction(self.actionNewGroup)
        self.toolBar.addAction(self.actionAddGroup)
        self.toolBar.addAction(self.actionCopyGroup)
        self.toolBar.addAction(self.actionRemoveGroup)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNewCase)
        self.toolBar.addAction(self.actionAddCase)
        self.toolBar.addAction(self.actionCopyCase)
        self.toolBar.addAction(self.actionRemoveCase)

        self.retranslateUi(ProjectsMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ProjectsMainWindow)

    def retranslateUi(self, ProjectsMainWindow):
        _translate = QtCore.QCoreApplication.translate
        ProjectsMainWindow.setWindowTitle(_translate("ProjectsMainWindow", "项目管理器"))
        self.pushButton_projectChoise.setText(_translate("ProjectsMainWindow", "工程"))
        self.toolBar.setWindowTitle(_translate("ProjectsMainWindow", "toolBar"))
        self.actionNewCase.setText(_translate("ProjectsMainWindow", "新建CASE"))
        self.actionNewCase.setToolTip(_translate("ProjectsMainWindow", "新建CASE"))
        self.actionCopyCase.setText(_translate("ProjectsMainWindow", "复制CASE"))
        self.actionCopyCase.setToolTip(_translate("ProjectsMainWindow", "复制CASE"))
        self.actionAddCase.setText(_translate("ProjectsMainWindow", "添加CASE"))
        self.actionAddCase.setToolTip(_translate("ProjectsMainWindow", "添加CASE"))
        self.actionRemoveCase.setText(_translate("ProjectsMainWindow", "移除Case"))
        self.actionRemoveCase.setToolTip(_translate("ProjectsMainWindow", "移除Case"))
        self.actionNewGroup.setText(_translate("ProjectsMainWindow", "新建组"))
        self.actionNewGroup.setToolTip(_translate("ProjectsMainWindow", "新建组"))
        self.actionAddGroup.setText(_translate("ProjectsMainWindow", "添加组"))
        self.actionAddGroup.setToolTip(_translate("ProjectsMainWindow", "添加组"))
        self.actionCopyGroup.setText(_translate("ProjectsMainWindow", "复制组"))
        self.actionCopyGroup.setToolTip(_translate("ProjectsMainWindow", "复制组"))
        self.actionRemoveGroup.setText(_translate("ProjectsMainWindow", "移除组"))
        self.actionRemoveGroup.setToolTip(_translate("ProjectsMainWindow", "移除组"))

import PyDatcomLab_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectsMainWindow = QtWidgets.QMainWindow()
    ui = Ui_ProjectsMainWindow()
    ui.setupUi(ProjectsMainWindow)
    ProjectsMainWindow.show()
    sys.exit(app.exec_())

