import  os,sys
from PyQt5 import QtCore,QtWidgets,QtGui
from PyDatcom.DatcomWidgets.SYNTHS import SYNTHSUI
from  xml.dom.minidom import Document

class SYNTHS(QtWidgets.QWidget):
    def __init__(self):
        super(SYNTHS,self).__init__()
        self.Ui = SYNTHSUI.Ui_Form()
        self.Ui.setupUi(self)
        self.initiate()
    def initiate(self):
        path = os.path.abspath(os.path.dirname(sys.argv[0]))
        path = path.rstrip("\\SYNTHSz")  #remove the SYNTHS in the path
        path2 = "\\rc\\SYNTHS.png"
        filePath = path + path2
        self.Ui.HINAX.setEnabled(False)
        icon = QtGui.QPixmap(filePath)
        icon2 = icon.scaled(500,400,0,0)
        self.Ui.pictureSYNTHS.setPixmap(icon2)
        self.Ui.XCG.setText('')
        self.Ui.ZCG.setText('')
        self.Ui.XW.setText('')
        self.Ui.ZW.setText('')
        self.Ui.XCG.setText('')
        self.Ui.ALIW.setText('')
        self.Ui.XH.setText('')
        self.Ui.ZH.setText('')
        self.Ui.ALIH.setText('')
        self.Ui.HINAX.setText('')
        self.Ui.XV.setText('')
        self.Ui.ZV.setText('')
        self.Ui.XVF.setText('')
        self.Ui.ZVF.setText('')
        self.Ui.SCALE.setText('')

    def xmlSYNTHS(self):
        doc = Document()
        nameListSYNTHS = doc.createElement('NameList')
        nameListSYNTHS.setAttribute('Name', "SYNTHS")
        doc.appendChild(nameListSYNTHS)
        if self.Ui.XCG.text()!='':
            XCG = doc.createElement('Variable')
            XCG.setAttribute('Name', "XCG")
            XCG.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(XCG)
            XCG_value = doc.createElement('Value')
            XCG_value_text = doc.createTextNode(str(self.Ui.XCG.text()))
            XCG.appendChild(XCG_value)
            XCG_value.appendChild(XCG_value_text)
        if self.Ui.ZCG.text() != '':
            ZCG = doc.createElement('Variable')
            ZCG.setAttribute('Name', "ZCG")
            ZCG.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(ZCG)
            ZCG_value = doc.createElement('Value')
            ZCG_value_text = doc.createTextNode(str(self.Ui.ZCG.text()))
            ZCG.appendChild(ZCG_value)
            ZCG_value.appendChild(ZCG_value_text)
        if self.Ui.XW.text() != '':
            XW = doc.createElement('Variable')
            XW.setAttribute('Name', "XW")
            XW.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(XW)
            XW_value = doc.createElement('Value')
            XW_value_text = doc.createTextNode(str(self.Ui.XW.text()))
            XW.appendChild(XW_value)
            XW_value.appendChild(XW_value_text)
        if self.Ui.ZW.text() != '':
            ZW = doc.createElement('Variable')
            ZW.setAttribute('Name', "ZW")
            ZW.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(ZW)
            ZW_value = doc.createElement('Value')
            ZW_value_text = doc.createTextNode(str(self.Ui.ZW.text()))
            ZW.appendChild(ZW_value)
            ZW_value.appendChild(ZW_value_text)
        if self.Ui.ALIW.text() != '':
            ALIW = doc.createElement('Variable')
            ALIW.setAttribute('Name', "ALIW")
            ALIW.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(ALIW)
            ALIW_value = doc.createElement('Value')
            ALIW_value_text = doc.createTextNode(str(self.Ui.ALIW.text()))
            ALIW.appendChild(ALIW_value)
            ALIW_value.appendChild(ALIW_value_text)
        if self.Ui.XH.text() != '':
            XH = doc.createElement('Variable')
            XH.setAttribute('Name', "XH")
            XH.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(XH)
            XH_value = doc.createElement('Value')
            XH_value_text = doc.createTextNode(str(self.Ui.XH.text()))
            XH.appendChild(XH_value)
            XH_value.appendChild(XH_value_text)
        if self.Ui.ZH.text() != '':
            ZH = doc.createElement('Variable')
            ZH.setAttribute('Name', "ZH")
            ZH.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(ZH)
            ZH_value = doc.createElement('Value')
            ZH_value_text = doc.createTextNode(str(self.Ui.ZH.text()))
            ZH.appendChild(ZH_value)
            ZH_value.appendChild(ZH_value_text)
        if self.Ui.ALIH.text() != '':
            ALIH = doc.createElement('Variable')
            ALIH.setAttribute('Name', "ALIH")
            ALIH.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(ALIH)
            ALIH_value = doc.createElement('Value')
            ALIH_value_text = doc.createTextNode(str(self.Ui.ALIH.text()))
            ALIH.appendChild(ALIH_value)
            ALIH_value.appendChild(ALIH_value_text)
        if self.Ui.checkBox_HINAX.checkState()==QtCore.Qt.Checked:
            HINAX = doc.createElement('Variable')
            HINAX.setAttribute('Name', "HINAX")
            HINAX.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(HINAX)
            HINAX_value = doc.createElement('Value')
            HINAX_value_text = doc.createTextNode(str(self.Ui.HINAX.text()))
            HINAX.appendChild(HINAX_value)
            HINAX_value.appendChild(HINAX_value_text)
        if self.Ui.XV.text() != '':
            XV = doc.createElement('Variable')
            XV.setAttribute('Name', "XV")
            XV.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(XV)
            XV_value = doc.createElement('Value')
            XV_value_text = doc.createTextNode(str(self.Ui.XV.text()))
            XV.appendChild(XV_value)
            XV_value.appendChild(XV_value_text)
        if self.Ui.ZV.text() != '':
            ZV = doc.createElement('Variable')
            ZV.setAttribute('Name', "ZV")
            ZV.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(ZV)
            ZV_value = doc.createElement('Value')
            ZV_value_text = doc.createTextNode(str(self.Ui.ZV.text()))
            ZV.appendChild(ZV_value)
            ZV_value.appendChild(ZV_value_text)
        if self.Ui.XVF.text() != '':
            XVF = doc.createElement('Variable')
            XVF.setAttribute('Name', "XVF")
            XVF.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(XVF)
            XVF_value = doc.createElement('Value')
            XVF_value_text = doc.createTextNode(str(self.Ui.XVF.text()))
            XVF.appendChild(XVF_value)
            XVF_value.appendChild(XVF_value_text)
        if self.Ui.ZVF.text() != '':
            ZVF = doc.createElement('Variable')
            ZVF.setAttribute('Name', "ZVF")
            ZVF.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(ZVF)
            ZVF_value = doc.createElement('Value')
            ZVF_value_text = doc.createTextNode(str(self.Ui.ZVF.text()))
            ZVF.appendChild(ZVF_value)
            ZVF_value.appendChild(ZVF_value_text)
        if self.Ui.SCALE.text() != '':
            SCALE = doc.createElement('Variable')
            SCALE.setAttribute('Name', "SCALE")
            SCALE.setAttribute('StartIndex', "1")
            nameListSYNTHS.appendChild(SCALE)
            SCALE_value = doc.createElement('Value')
            SCALE_value_text = doc.createTextNode(str(self.Ui.SCALE.text()))
            SCALE.appendChild(SCALE_value)
            SCALE_value.appendChild(SCALE_value_text)
        VERTUP = doc.createElement('Variable')
        VERTUP.setAttribute('Name', "VERTUP")
        VERTUP.setAttribute('StartIndex', "1")
        nameListSYNTHS.appendChild(VERTUP)
        VERTUP_value = doc.createElement('Value')
        if self.Ui.VERTUP.currentIndex()==0:
            VERTUP_value_text = doc.createTextNode(str(".TRUE."))
        else:
            VERTUP_value_text = doc.createTextNode(str(".FALSE."))
        VERTUP.appendChild(VERTUP_value)
        VERTUP_value.appendChild(VERTUP_value_text)

        return (nameListSYNTHS)
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = SYNTHS()
    window.show()
    sys.exit(app.exec_())