# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\linger\AnacondaProjects\PyDatcomLabHelper\HelperBrowses.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PyMarkDownHelper(object):
    def setupUi(self, PyMarkDownHelper):
        PyMarkDownHelper.setObjectName("PyMarkDownHelper")
        PyMarkDownHelper.resize(882, 645)
        self.centralWidget = QtWidgets.QWidget(PyMarkDownHelper)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tabWidget_lift = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_lift.sizePolicy().hasHeightForWidth())
        self.tabWidget_lift.setSizePolicy(sizePolicy)
        self.tabWidget_lift.setObjectName("tabWidget_lift")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_search = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_search.sizePolicy().hasHeightForWidth())
        self.lineEdit_search.setSizePolicy(sizePolicy)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.pushButton_Search = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Search.sizePolicy().hasHeightForWidth())
        self.pushButton_Search.setSizePolicy(sizePolicy)
        self.pushButton_Search.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Search.setIcon(icon)
        self.pushButton_Search.setObjectName("pushButton_Search")
        self.horizontalLayout.addWidget(self.pushButton_Search)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.treeView_Helper = QtWidgets.QTreeView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView_Helper.sizePolicy().hasHeightForWidth())
        self.treeView_Helper.setSizePolicy(sizePolicy)
        self.treeView_Helper.setObjectName("treeView_Helper")
        self.verticalLayout.addWidget(self.treeView_Helper)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tabWidget_lift.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_lift.addTab(self.tab_2, "")
        self.tabWidget_right = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_right.setObjectName("tabWidget_right")
        self.tab_Browser = QtWidgets.QWidget()
        self.tab_Browser.setObjectName("tab_Browser")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_Browser)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_right.addTab(self.tab_Browser, "")
        self.verticalLayout_4.addWidget(self.splitter)
        PyMarkDownHelper.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(PyMarkDownHelper)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 882, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        PyMarkDownHelper.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(PyMarkDownHelper)
        self.statusBar.setObjectName("statusBar")
        PyMarkDownHelper.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(PyMarkDownHelper)
        self.toolBar.setObjectName("toolBar")
        PyMarkDownHelper.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpenDirectory = QtWidgets.QAction(PyMarkDownHelper)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/bokeh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenDirectory.setIcon(icon1)
        self.actionOpenDirectory.setObjectName("actionOpenDirectory")
        self.actionExit = QtWidgets.QAction(PyMarkDownHelper)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.menu.addAction(self.actionOpenDirectory)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.toolBar.addAction(self.actionOpenDirectory)

        self.retranslateUi(PyMarkDownHelper)
        self.tabWidget_lift.setCurrentIndex(0)
        self.tabWidget_right.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PyMarkDownHelper)

    def retranslateUi(self, PyMarkDownHelper):
        _translate = QtCore.QCoreApplication.translate
        PyMarkDownHelper.setWindowTitle(_translate("PyMarkDownHelper", "帮助"))
        self.tabWidget_lift.setTabText(self.tabWidget_lift.indexOf(self.tab), _translate("PyMarkDownHelper", "浏览"))
        self.tabWidget_lift.setTabText(self.tabWidget_lift.indexOf(self.tab_2), _translate("PyMarkDownHelper", "标签"))
        self.tabWidget_right.setTabText(self.tabWidget_right.indexOf(self.tab_Browser), _translate("PyMarkDownHelper", "浏览"))
        self.menu.setTitle(_translate("PyMarkDownHelper", "文件"))
        self.menu_2.setTitle(_translate("PyMarkDownHelper", "帮助"))
        self.toolBar.setWindowTitle(_translate("PyMarkDownHelper", "toolBar"))
        self.actionOpenDirectory.setText(_translate("PyMarkDownHelper", "打开目录(&o)"))
        self.actionExit.setText(_translate("PyMarkDownHelper", "退出"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PyMarkDownHelper = QtWidgets.QMainWindow()
    ui = Ui_PyMarkDownHelper()
    ui.setupUi(PyMarkDownHelper)
    PyMarkDownHelper.show()
    sys.exit(app.exec_())

